name: Create torrent
on:
  push:
    branches:
      - master
      
env:
  name: "Hercules.in.New.York.1969.1080p.BluRay.x264"
  comment: "Hercules.in.New.York.1969.1080p.BluRay.x264"
  url: https://dlsvfree.sonicbit.net/file/dl2/aWgvMUZ4WnlKVnlKcURnYkY2RUFIRWUyVXFDTnVUZExnMnpaa2NQNkxqSEVRM1F5TTF2aGhCN05oalFvNy9zSGxaQTZvZE8xTWwvRi9GbXVNQ3pCNkVFYTFlbCtNNDZtSDJFZjAzUklidnpMT3loNldxMkhDTXNUTGxzNHNTcUd1N1RJb1RxWTRUS2ZaVURRNVJsOTRZdFJka1h2QXhKbURSS3ZCZ09iWXNJcEQ1b3FmbWQ2TmtrbzRySUltdGtH/Hercules.in.New.York.1969.1080p.BluRay.x264.YIFY.mp4
  file_name: "Hercules.in.New.York.1969.1080p.BluRay.x264.YIFY.mp4"
  piece_size: 20 # Check the README.md for recommended piece size
      
jobs:
  create:
    runs-on: ubuntu-20.04
    steps:
      - name: Install mktorrent
        run: sudo apt-get install mktorrent
        
      - name: Download file
        run: wget -nv -O "$file_name" "$url"
        
      - name: Create torrent using mktorrent
        run: mktorrent -c "$comment" -l $piece_size -o "${name}.torrent" -w "$url" "$file_name"
        
      - name: Upload torrent file
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.name }}
          path: ${{ env.name }}.torrent
