name: Create torrent
on:
  push:
    branches:
      - master
      
env:
  name: "Delusions.Of.Grandeur.1971.1080p.BluRay.x264.AAC5.1"
  comment: "Delusions.Of.Grandeur.1971.1080p.BluRay.x264.AAC5.1"
  url: https://dlsv6.sonicbit.net/file/dl2/TXQ2UHNNQzBZWjdYdk5VbFg4eEhjUFZFTXdKclZSak9BYWc1R1k2MTJTd2tjcEVHOTdheW1Xc3VReG9abEt3S3FLYW1KRkZBVGVLMTVscWFacGtLQ0xNWWtWUm55TnYybmdSeDVhaDFTUWM5QldMblFUUXpJRzBjTlBseVVTeE1oQjNkSDl6OXhzR3Q4MGRSLzBGRDV6UEJDdGttdDlOSmhBUUI1eFlLOFNERS9yR1RrVStYMC9CMUx3bE8wWnRTeEVDakRNNjVNSW5FWW1kZjhpMTA1eGxGdG9TZ0ZzWWQwVjVZV1UxWHdabz0=/Delusions.Of.Grandeur.1971.1080p.BluRay.x264.AAC5.1-[YTS.MX].mp4
  file_name: "Delusions.Of.Grandeur.1971.1080p.BluRay.x264.AAC5.1-[YTS.MX].mp4"
  piece_size: 20 # Check the README.md for recommended piece size
      
jobs:
  create:
    runs-on: ubuntu-20.04
    steps:
      - name: Install mktorrent
        run: sudo apt-get install mktorrent
        
      - name: Download file
        run: wget -nv -O "$file_name" "$url"
        
      - name: Create torrent using mktorrent
        run: mktorrent -c "$comment" -l $piece_size -o "${name}.torrent" -w "$url" "$file_name"
        
      - name: Upload torrent file
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.name }}
          path: ${{ env.name }}.torrent
