name: Create torrent
on:
  push:
    branches:
      - master
      
env:
  name: "A New Leaf (1971)"
  comment: "A New Leaf (1971)"
  url: https://dlsv6.sonicbit.net/dl/zip2/Wkg1TjhjcVYxblNRRlRqWG13YkJ3WUVESzArSml5QWFqMm5pYWEyR2lLbEE0NEdGVGg0YU9Oa3U0L2cxdk5EVg==/DA91ABF162BCA213AFC2FCBFD9B49813ECEF50CF/A%20New%20Leaf%20(1971)%201080p.zip
  file_name: "A New Leaf (1971) [1080p].zip"
  piece_size: 20 # Check the README.md for recommended piece size
      
jobs:
  create:
    runs-on: ubuntu-20.04
    steps:
      - name: Install mktorrent
        run: sudo apt-get install mktorrent
        
      - name: Download file
        run: wget -nv -O "$file_name" "$url"
        
      - name: Create torrent using mktorrent
        run: mktorrent -c "$comment" -l $piece_size -o "${name}.torrent" -w "$url" "$file_name"
        
      - name: Upload torrent file
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.name }}
          path: ${{ env.name }}.torrent
