name: Create torrent
on:
  push:
    branches:
      - master
      
env:
  name: "Villain.1971.1080p.BluRay.x264.AAC"
  comment: "Villain.1971.1080p.BluRay.x264.AAC"
  url: https://dlsv6.sonicbit.net/file/dl2/TXQ2UHNNQzBZWjdYdk5VbFg4eEhjUFZFTXdKclZSak9BYWc1R1k2MTJTelFTVGNtVkpxZTFudlRZU1VOc2NOMkRYVkQvbFEzeWRYZGRPMERCTDhzTFc3cGFNZXhoUnJqUk90NGlsajQxMFZkNHlyZUlVYk1oNDh1bnc3NEFJUHduaklnc2V4TVVjeTdJWjFnM1Y4Zmd2TVIxY1ZGWmxUaHZDdjVqb21ZWmxKVlg5SHEwVm9RcjZhRWY2cWpUa2dx/Villain.1971.1080p.BluRay.x264.AAC-[YTS.MX].mp4
  file_name: "Villain.1971.1080p.BluRay.x264.AAC-[YTS.MX].mp4"
  piece_size: 20 # Check the README.md for recommended piece size
      
jobs:
  create:
    runs-on: ubuntu-20.04
    steps:
      - name: Install mktorrent
        run: sudo apt-get install mktorrent
        
      - name: Download file
        run: wget -nv -O "$file_name" "$url"
        
      - name: Create torrent using mktorrent
        run: mktorrent -c "$comment" -l $piece_size -o "${name}.torrent" -w "$url" "$file_name"
        
      - name: Upload torrent file
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.name }}
          path: ${{ env.name }}.torrent
