name: Create torrent
on:
  push:
    branches:
      - master
      
env:
  name: "Toys Are Not For Children (1972)"
  comment: "Toys Are Not For Children (1972)"
  url: https://dlsv6.sonicbit.net/dl/zip2/SnZtZTRjd2tHTktnemo3dmtFS1Q3TzFmN1pmYUtRR3BzRFoyNDZNeWpIWmF4MEZtaU95ZTVXbk1jUnYvYnp2WmZ1Z2EvbGNSNlFteVdSRFM4eWhQT0lEajNwUkoxQW5hSkhRVXJHaFFRS009/4BE02B0070D5736A942691C3AF535B421EB0FC1C/Toys%20Are%20Not%20For%20Children%20(1972)%20BluRay%20[1080p]%20[YTS.LT].zip
  file_name: "Toys Are Not For Children (1972) [BluRay] [1080p] [YTS.LT].zip"
  piece_size: 20 # Check the README.md for recommended piece size
      
jobs:
  create:
    runs-on: ubuntu-20.04
    steps:
      - name: Install mktorrent
        run: sudo apt-get install mktorrent
        
      - name: Download file
        run: wget -nv -O "$file_name" "$url"
        
      - name: Create torrent using mktorrent
        run: mktorrent -c "$comment" -l $piece_size -o "${name}.torrent" -w "$url" "$file_name"
        
      - name: Upload torrent file
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.name }}
          path: ${{ env.name }}.torrent
