name: Create torrent
on:
  push:
    branches:
      - master
      
env:
  name: "A Severed Head (1971)"
  comment: "A Severed Head (1971)"
  url: https://dlsv6.sonicbit.net/dl/zip2/bzhtOXNiQUZsNWtNaXdGTDJiVStQMnpBU1NyRG85UFRPL29sZzNlbjFDMlhEaVkwaHhGTVFyY1NrTnFhZE5SKzArQlp0Nm92MnkrcFlEVVJkMms4blE9PQ==/6A8SG9A6G87AS78G6/A%20Severed%20Head%20(1971)%20BluRay%20[1080p]%20[YTS.AM].zip
  file_name: "A Severed Head (1971) [BluRay] [1080p] [YTS.AM].zip"
  piece_size: 20 # Check the README.md for recommended piece size
      
jobs:
  create:
    runs-on: ubuntu-20.04
    steps:
      - name: Install mktorrent
        run: sudo apt-get install mktorrent
        
      - name: Download file
        run: wget -nv -O "$file_name" "$url"
        
      - name: Create torrent using mktorrent
        run: mktorrent -c "$comment" -l $piece_size -o "${name}.torrent" -w "$url" "$file_name"
        
      - name: Upload torrent file
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.name }}
          path: ${{ env.name }}.torrent
