name: Create torrent
on:
  push:
    branches:
      - master
      
env:
  name: "See.You.At.Mao.1970.1080p.BluRay.x264"
  comment: "See.You.At.Mao.1970.1080p.BluRay.x264"
  url: https://dlsv6.sonicbit.net/file/dl2/TXQ2UHNNQzBZWjdYdk5VbFg4eEhjUFZFTXdKclZSak9BYWc1R1k2MTJTeTZiVUFZWk5tYjdUQmpOT3F6dmo5YWdDUk5oYXFkYjZVNVVzNGRhbFk4ZVhmcE80SUd6M0NrcFdVN0w1bDdQdlNKWld0VVV6VlZmbDlmbVhFR25YMEYvdnJBR3BSR1B3bVBhREhUcHdjRmhXQit3WldzZm96VHVvU2prNFVtZVJtcXJBV25UZzJMMWEyVTNOK0pTeGFQ/See.You.At.Mao.1970.1080p.BluRay.x264-[YTS.AM].mp4
  file_name: "See.You.At.Mao.1970.1080p.BluRay.x264-[YTS.AM].mp4"
  piece_size: 20 # Check the README.md for recommended piece size
      
jobs:
  create:
    runs-on: ubuntu-20.04
    steps:
      - name: Install mktorrent
        run: sudo apt-get install mktorrent
        
      - name: Download file
        run: wget -nv -O "$file_name" "$url"
        
      - name: Create torrent using mktorrent
        run: mktorrent -c "$comment" -l $piece_size -o "${name}.torrent" -w "$url" "$file_name"
        
      - name: Upload torrent file
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.name }}
          path: ${{ env.name }}.torrent
