name: Create torrent
on:
  push:
    branches:
      - master
      
env:
  name: "Gumshoe (1971)"
  comment: "Gumshoe (1971)"
  url: https://dlsv6.sonicbit.net/dl/zip2/N0ZoR2VYdDFGWUJzVXh0a3dQbWlEYitPRmRPVmw0N2pXUXQyM1VJaFRJRDFnbHEwS0pFRzNzU3dlS2JOS3VFQ1B6NGR2N0JFajVEWDJxYXJ6dEhkTEE9PQ==/38B613F7AC2B90B5225B3AC285DAC062D19B3D14/Gumshoe%20(1971)%20BluRay%20[1080p]%20[YTS.AM].zip
  file_name: "Gumshoe (1971) [BluRay] [1080p] [YTS.AM].zip"
  piece_size: 20 # Check the README.md for recommended piece size
      
jobs:
  create:
    runs-on: ubuntu-20.04
    steps:
      - name: Install mktorrent
        run: sudo apt-get install mktorrent
        
      - name: Download file
        run: wget -nv -O "$file_name" "$url"
        
      - name: Create torrent using mktorrent
        run: mktorrent -c "$comment" -l $piece_size -o "${name}.torrent" -w "$url" "$file_name"
        
      - name: Upload torrent file
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.name }}
          path: ${{ env.name }}.torrent
