name: Create torrent
on:
  push:
    branches:
      - master
      
env:
  name: "The Anderson Tapes (1971)"
  comment: "The Anderson Tapes (1971)"
  url: https://dlsv6.sonicbit.net/dl/zip2/cXRad0hlU1FNejNGSDlXTFpFcSszcEE3M1pkaDh0MlJ4bFlHQm5ibTJrbXp3S3BZbnJKUElJMXlNUDYrOW9tSUdZeTZFam1tNU1lcUFyUTNyMkRINERhcEVWN05VL1JwNEJYZEdMd2M3WVk9/66162A2E1FB78218D4F04FFAF73F49083BB2FE54/The%20Anderson%20Tapes%20(1971)%201080p%20[BluRay]%20[5.1]%20[YTS.MX].zip
  file_name: "The Anderson Tapes (1971) [1080p] [BluRay] [5.1] [YTS.MX].zip"
  piece_size: 20 # Check the README.md for recommended piece size
      
jobs:
  create:
    runs-on: ubuntu-20.04
    steps:
      - name: Install mktorrent
        run: sudo apt-get install mktorrent
        
      - name: Download file
        run: wget -nv -O "$file_name" "$url"
        
      - name: Create torrent using mktorrent
        run: mktorrent -c "$comment" -l $piece_size -o "${name}.torrent" -w "$url" "$file_name"
        
      - name: Upload torrent file
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.name }}
          path: ${{ env.name }}.torrent
