name: Create torrent
on:
  push:
    branches:
      - master
      
env:
  name: "In.Enemy.Country.1968"
  comment: "In.Enemy.Country.1968"
  url: http://45.162.231.181:3000/download/61811846-6047-4d81-84d1-f553d3bfde7b/in-enemy-country-1968.mkv
  file_name: "In.Enemy.Country.1968.mkv"
  piece_size: 20 # Check the README.md for recommended piece size
      
jobs:
  create:
    runs-on: ubuntu-20.04
    steps:
      - name: Install mktorrent
        run: sudo apt-get install mktorrent
        
      - name: Download file
        run: wget -nv -O "$file_name" "$url"
        
      - name: Create torrent using mktorrent
        run: mktorrent -c "$comment" -l $piece_size -o "${name}.torrent" -w "$url" "$file_name"
        
      - name: Upload torrent file
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.name }}
          path: ${{ env.name }}.torrent
