name: Create torrent
on:
  push:
    branches:
      - master
      
env:
  name: "Play It Again Sam (1972)"
  comment: "Play It Again Sam (1972)"
  url: https://dlsv6.sonicbit.net/dl/zip2/djhaeGQ4YmFsSHJmS1BJTlR3VUFocHhKbkZTZ3pyYkh6SjBuSE5VUlNYVmpua3c3SkNnK2VsRXIxcDl4Ymlsa2VLNXoxODNTc3J6dkdJRkNtUlF0eHc9PQ==/6A8SG9A6G87AS78G6/Play%20It%20Again%20Sam%20(1972)%20720p%20[WEBRip]%20[YTS.MX].zip
  file_name: "Play It Again Sam (1972) [720p] [WEBRip] [YTS.MX].zip"
  piece_size: 20 # Check the README.md for recommended piece size
      
jobs:
  create:
    runs-on: ubuntu-20.04
    steps:
      - name: Install mktorrent
        run: sudo apt-get install mktorrent
        
      - name: Download file
        run: wget -nv -O "$file_name" "$url"
        
      - name: Create torrent using mktorrent
        run: mktorrent -c "$comment" -l $piece_size -o "${name}.torrent" -w "$url" "$file_name"
        
      - name: Upload torrent file
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.name }}
          path: ${{ env.name }}.torrent
