name: Create torrent
on:
  push:
    branches:
      - master
      
env:
  name: "Chatos Land (1972)"
  comment: "Chatos Land (1972)"
  url: https://dlsv6.sonicbit.net/dl/zip2/aGlLUkFiUjl5cUlKcHZaVFo0TEdiUGhhbFNWYVlhYXdzQ20xNlRyNUhBZFFhVWFmcHAyLzB6ZDBOQlQ0ZE84SFRFclI3Skx6TWVPdm5XYWtwZFZFMVE9PQ==/6A8SG9A6G87AS78G6/Chatos%20Land%20(1972)%201080p%20[BluRay]%20[YTS.MX].zip
  file_name: "Chatos Land (1972) [1080p] [BluRay] [YTS.MX].zip"
  piece_size: 20 # Check the README.md for recommended piece size
      
jobs:
  create:
    runs-on: ubuntu-20.04
    steps:
      - name: Install mktorrent
        run: sudo apt-get install mktorrent
        
      - name: Download file
        run: wget -nv -O "$file_name" "$url"
        
      - name: Create torrent using mktorrent
        run: mktorrent -c "$comment" -l $piece_size -o "${name}.torrent" -w "$url" "$file_name"
        
      - name: Upload torrent file
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.name }}
          path: ${{ env.name }}.torrent
