name: Create torrent
on:
  push:
    branches:
      - master
      
env:
  name: "Roy.Colt.Winchester.Jack.1970.1080p.BluRay.x264.AAC"
  comment: "Roy.Colt.Winchester.Jack.1970.1080p.BluRay.x264.AAC"
  url: https://dlsv6.sonicbit.net/file/dl2/TXQ2UHNNQzBZWjdYdk5VbFg4eEhjUFZFTXdKclZSak9BYWc1R1k2MTJTelFyVFlRODB5Y0laaXAxeDB3Q2U2UXpWQTZ5Z1llVTBEZ05TcWppU1FVYnA0VWJUd0VlWmxUdEcyWG1kaW9iaWJZZWZMZGJRTUI4RGhEQTFoNjNTekRSYXNIUnpjdi96N3hhMUpkOWNNMFdaNmNPdUJRcjdDek9WeGptbjlkVFU0cTNnMktVMWEveEIxMHRkR3JJMU94SW93MjUvK0sxa0ZldkFOMDN0SWx5NVMwNzhwUW9Bb2xxeEFMQWJjUkJQdz0=/Roy.Colt.Winchester.Jack.1970.1080p.BluRay.x264.AAC-[YTS.MX].mp4
  file_name: "Roy.Colt.Winchester.Jack.1970.1080p.BluRay.x264.AAC-[YTS.MX].mp4"
  piece_size: 20 # Check the README.md for recommended piece size
      
jobs:
  create:
    runs-on: ubuntu-20.04
    steps:
      - name: Install mktorrent
        run: sudo apt-get install mktorrent
        
      - name: Download file
        run: wget -nv -O "$file_name" "$url"
        
      - name: Create torrent using mktorrent
        run: mktorrent -c "$comment" -l $piece_size -o "${name}.torrent" -w "$url" "$file_name"
        
      - name: Upload torrent file
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.name }}
          path: ${{ env.name }}.torrent
