name: Create torrent
on:
  push:
    branches:
      - master
      
env:
  name: "Requiem For A Vampire (1971)"
  comment: "Requiem For A Vampire (1971)"
  url: https://dlsv6.sonicbit.net/dl/zip2/UDF3T2NWZkNrUmt1bkpaaHRvNXpNZjdFQ0FZanJTOU5wNkE2ZXc1Zk9zN3J4UTZQUTR0d0dqcGxoL1h4bVkrM2lLNDFNTm5kUGpYTFlhNmJLMGtweDFxemZzQWcyZzR5Q3E3ak9EejBHY3c9/1D15E7F42CF1D0AD73B509125A7116604DB69812/Requiem%20For%20A%20Vampire%20(1971)%20BluRay%20[1080p]%20[YTS.AM].zip
  file_name: "Requiem For A Vampire (1971) [BluRay] [1080p] [YTS.AM].zip"
  piece_size: 20 # Check the README.md for recommended piece size
      
jobs:
  create:
    runs-on: ubuntu-20.04
    steps:
      - name: Install mktorrent
        run: sudo apt-get install mktorrent
        
      - name: Download file
        run: wget -nv -O "$file_name" "$url"
        
      - name: Create torrent using mktorrent
        run: mktorrent -c "$comment" -l $piece_size -o "${name}.torrent" -w "$url" "$file_name"
        
      - name: Upload torrent file
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.name }}
          path: ${{ env.name }}.torrent
