name: Create torrent
on:
  push:
    branches:
      - master
      
env:
  name: "If Footmen Tire You What Will Horses Do  (1971)"
  comment: "If Footmen Tire You What Will Horses Do  (1971)"
  url: https://dlsv6.sonicbit.net/dl/zip2/dVpGTEFvRlZZTVc4UmFoR1R4QitSYzJoTGtETE5TbFlyV1BQQnNWZ0ZVWExTL0hkT29WQkhrVmluWE90dG9tcFJkdWVpc1NFYTlHZ2tCK3krRDYzRXBXY25nNFhtYXBPZ0diSmlSaEkzUytleFVPTjVpUE0wb2ZxNEJvOSsvS1o=/890D92AB00453EC2E5F0EC6CC8EA01B47F00E032/If%20Footmen%20Tire%20You%20What%20Will%20Horses%20Do%20%20(1971)%20WEBRip%20[1080p]%20[YTS.AM].zip
  file_name: "If Footmen Tire You What Will Horses Do  (1971) [WEBRip] [1080p] [YTS.AM].zip"
  piece_size: 20 # Check the README.md for recommended piece size
      
jobs:
  create:
    runs-on: ubuntu-20.04
    steps:
      - name: Install mktorrent
        run: sudo apt-get install mktorrent
        
      - name: Download file
        run: wget -nv -O "$file_name" "$url"
        
      - name: Create torrent using mktorrent
        run: mktorrent -c "$comment" -l $piece_size -o "${name}.torrent" -w "$url" "$file_name"
        
      - name: Upload torrent file
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.name }}
          path: ${{ env.name }}.torrent
