name: Create torrent
on:
  push:
    branches:
      - master
      
env:
  name: "Trafic.1971.1080p.BluRay.x264"
  comment: "Trafic.1971.1080p.BluRay.x264"
  url: https://dlsv6.sonicbit.net/file/dl2/TXQ2UHNNQzBZWjdYdk5VbFg4eEhjUFZFTXdKclZSak9BYWc1R1k2MTJTendDVFJldVlZQkM0VzF4cDFsS1BXbE1WcGtoRy9LVDVLZUVZWVd3RnFkZmd2TktWbEJxRU9hZzJEQlZydmg4UXpqMk9tZG1xcmhIQ3lhRnV1QS9RejFHUCtPNXNBSDZIS1k4OGRzR0I2dUtxMnF2NjZlazVtVnV2b2dJdUxwVUI4PQ==/Trafic.1971.1080p.BluRay.x264-[YTS.LT].mp4
  file_name: "Trafic.1971.1080p.BluRay.x264-[YTS.LT].mp4"
  piece_size: 20 # Check the README.md for recommended piece size
      
jobs:
  create:
    runs-on: ubuntu-20.04
    steps:
      - name: Install mktorrent
        run: sudo apt-get install mktorrent
        
      - name: Download file
        run: wget -nv -O "$file_name" "$url"
        
      - name: Create torrent using mktorrent
        run: mktorrent -c "$comment" -l $piece_size -o "${name}.torrent" -w "$url" "$file_name"
        
      - name: Upload torrent file
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.name }}
          path: ${{ env.name }}.torrent
