name: Create torrent
on:
  push:
    branches:
      - master
      
env:
  name: "Cockeyed.Cowboys.Of.Calico.County.1970.1080p.WEBRip.x264"
  comment: "Cockeyed.Cowboys.Of.Calico.County.1970.1080p.WEBRip.x264"
  url: https://dlsvfree.sonicbit.net/file/dl2/aWgvMUZ4WnlKVnlKcURnYkY2RUFIRWZqYk1kNSsyR040VjloODJ3YnQ4V1pUNDlaMlltdVU2b0JaVnFJS0JUZEZHYklzekJMVnM4aytqazYwTWl0Q3hhWkRDOVJNbVp1eU5RczB3QlV0eVNtaWdBNUdtN0UyY0V0MHgwWmZtQWd4US9XMDlqV2VSdUQvR0ZseUpPTW0wVWUzNE5mSTB2VWVDenZ2dDRadlNyOTZ3OFR1MGxFdEtkWkZkMzJoOG9kR2dQSThjeGVlMCtwNWFyaVp5NkZuaVkzamRvL0czUTlTQXZSb2JreTllLzJjNU1iRFlENUpOS055YkdXNUxENQ==/Cockeyed.Cowboys.Of.Calico.County.1970.1080p.WEBRip.x264-[YTS.AM].mp4
  file_name: "Cockeyed.Cowboys.Of.Calico.County.1970.1080p.WEBRip.x264-[YTS.AM].mp4"
  piece_size: 20 # Check the README.md for recommended piece size
      
jobs:
  create:
    runs-on: ubuntu-20.04
    steps:
      - name: Install mktorrent
        run: sudo apt-get install mktorrent
        
      - name: Download file
        run: wget -nv -O "$file_name" "$url"
        
      - name: Create torrent using mktorrent
        run: mktorrent -c "$comment" -l $piece_size -o "${name}.torrent" -w "$url" "$file_name"
        
      - name: Upload torrent file
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.name }}
          path: ${{ env.name }}.torrent
