name: Create torrent
on:
  push:
    branches:
      - master
      
env:
  name: "Four.Times.That.Night.1971.1080p.BluRay.x264.AAC"
  comment: "Four.Times.That.Night.1971.1080p.BluRay.x264.AAC"
  url: https://dlsv6.sonicbit.net/file/dl2/TXQ2UHNNQzBZWjdYdk5VbFg4eEhjUFZFTXdKclZSak9BYWc1R1k2MTJTd2UzTXIra25qVVdSL3MwUFFFV2twakFDUDZnOHh4UFdhSEdYTHhXY3lWc3ZhQmUzbG00c0VtZHc0ak44R253bHBCaFQyRDBvc1dRQ2w5RkNISEJ3cUdOMHJyNkJoaDFsNTNmdXc5WkFQNzJXak5vbnhjUkNHejY5TXBVZjdIdytJMTFFenN5UEgxc09uK2VuUDljVVBUQkdiN0VNenpCOEROL3dQR05pSjlmN2p5SEd4Sks0L2duVTlwS3ozTTJVaz0=/Four.Times.That.Night.1971.1080p.BluRay.x264.AAC-[YTS.MX].mp4
  file_name: "Four.Times.That.Night.1971.1080p.BluRay.x264.AAC-[YTS.MX].mp4"
  piece_size: 20 # Check the README.md for recommended piece size
      
jobs:
  create:
    runs-on: ubuntu-20.04
    steps:
      - name: Install mktorrent
        run: sudo apt-get install mktorrent
        
      - name: Download file
        run: wget -nv -O "$file_name" "$url"
        
      - name: Create torrent using mktorrent
        run: mktorrent -c "$comment" -l $piece_size -o "${name}.torrent" -w "$url" "$file_name"
        
      - name: Upload torrent file
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.name }}
          path: ${{ env.name }}.torrent
