name: Create torrent
on:
  push:
    branches:
      - master
      
env:
  name: "Summer Of '42 (1971)"
  comment: "Summer Of '42 (1971)"
  url: https://dlsv6.sonicbit.net/dl/zip2/Q1pLbisyTlBKRStncmRQWjVud1N1ODJ5bHpNYTNRMnhHQXhhd0hUM2E4UTVSQ2V5dU9aZStyUUE1WWF1dzE0SUlaaDdRQnZvRnZDQnd6THZ1MjBsWGc9PQ==/91BC983EE4A402583CE5C57DE879757734D8476F/Summer%20Of%20'42%20(1971)%201080p%20[YTS.AG].zip
  file_name: "Summer Of '42 (1971) [1080p] [YTS.AG].zip"
  piece_size: 20 # Check the README.md for recommended piece size
      
jobs:
  create:
    runs-on: ubuntu-20.04
    steps:
      - name: Install mktorrent
        run: sudo apt-get install mktorrent
        
      - name: Download file
        run: wget -nv -O "$file_name" "$url"
        
      - name: Create torrent using mktorrent
        run: mktorrent -c "$comment" -l $piece_size -o "${name}.torrent" -w "$url" "$file_name"
        
      - name: Upload torrent file
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.name }}
          path: ${{ env.name }}.torrent
