name: Create torrent
on:
  push:
    branches:
      - master
      
env:
  name: "Execution Squad (1972)"
  comment: "Execution Squad (1972)"
  url: https://dlsv6.sonicbit.net/dl/zip2/M05ZZnlBdHRySUpLSlJ0NnM5K0trdkV6WGhyVXQxalNsb29HM3hjZWxvTjliUlU3bkxCeG9lSGRpeHJ5MkRKTDE1b0NjamF2Q09sc2VWY3ZpWUpLOXc9PQ==/1E266C133AFE2A54217C720251B8DB8C97F415D2/Execution%20Squad%20(1972)%20BluRay%20[1080p]%20[YTS.LT].zip
  file_name: "Execution Squad (1972) [BluRay] [1080p] [YTS.LT].zip"
  piece_size: 20 # Check the README.md for recommended piece size
      
jobs:
  create:
    runs-on: ubuntu-20.04
    steps:
      - name: Install mktorrent
        run: sudo apt-get install mktorrent
        
      - name: Download file
        run: wget -nv -O "$file_name" "$url"
        
      - name: Create torrent using mktorrent
        run: mktorrent -c "$comment" -l $piece_size -o "${name}.torrent" -w "$url" "$file_name"
        
      - name: Upload torrent file
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.name }}
          path: ${{ env.name }}.torrent
