name: Create torrent
on:
  push:
    branches:
      - master
      
env:
  name: "Blood From The Mummy's Tomb (1971)"
  comment: "Blood From The Mummy's Tomb (1971)"
  url: https://dlsv6.sonicbit.net/dl/zip2/dkVnVGlOd21IZVAwS1ZONG93eDd0N205RGNlQ0xCaXltSXg1VjFUb0k1SEQvdlJRL3c3OTFFK08zOVE2YVQrNlRJUlVWN2RjWHhGWHB3VTRBSURyMlIybmpXWGN5dGU4Mi9NVGhaMWpaWjA9/EE1A265A35E58CD14AA4F834F6AB940725C5386D/Blood%20From%20The%20Mummy's%20Tomb%20(1971)%20BluRay%20[1080p]%20[YTS.AM].zip
  file_name: "Blood From The Mummy's Tomb (1971) [BluRay] [1080p] [YTS.AM].zip"
  piece_size: 20 # Check the README.md for recommended piece size
      
jobs:
  create:
    runs-on: ubuntu-20.04
    steps:
      - name: Install mktorrent
        run: sudo apt-get install mktorrent
        
      - name: Download file
        run: wget -nv -O "$file_name" "$url"
        
      - name: Create torrent using mktorrent
        run: mktorrent -c "$comment" -l $piece_size -o "${name}.torrent" -w "$url" "$file_name"
        
      - name: Upload torrent file
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.name }}
          path: ${{ env.name }}.torrent
