name: Create torrent
on:
  push:
    branches:
      - master
      
env:
  name: "she.says.shes.innocent.1991"
  comment: "she.says.shes.innocent.1991"
  url: http://linkspremium.download/2F5F00C95/195.189.226.28/she.says.shes.innocent.1991.mkv
  file_name: "she.says.shes.innocent.1991.mkv"
  piece_size: 20 # Check the README.md for recommended piece size
      
jobs:
  create:
    runs-on: ubuntu-20.04
    steps:
      - name: Install mktorrent
        run: sudo apt-get install mktorrent
        
      - name: Download file
        run: wget -nv -O "$file_name" "$url"
        
      - name: Create torrent using mktorrent
        run: mktorrent -c "$comment" -l $piece_size -o "${name}.torrent" -w "$url" "$file_name"
        
      - name: Upload torrent file
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.name }}
          path: ${{ env.name }}.torrent
