name: Create torrent
on:
  push:
    branches:
      - master
      
env:
  name: "Terror.in.the.Mall.1998"
  comment: "Terror.in.the.Mall.1998"
  url: http://45.162.231.181:3000/download/8a83c67d-5162-4311-8a00-a69f11f13b4f/terror-in-the-mall-1998.mkv
  file_name: "Terror.in.the.Mall.1998.mkv"
  piece_size: 20 # Check the README.md for recommended piece size
      
jobs:
  create:
    runs-on: ubuntu-20.04
    steps:
      - name: Install mktorrent
        run: sudo apt-get install mktorrent
        
      - name: Download file
        run: wget -nv -O "$file_name" "$url"
        
      - name: Create torrent using mktorrent
        run: mktorrent -c "$comment" -l $piece_size -o "${name}.torrent" -w "$url" "$file_name"
        
      - name: Upload torrent file
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.name }}
          path: ${{ env.name }}.torrent
