name: Create torrent
on:
  push:
    branches:
      - master
      
env:
  name: "Vanishing.Point.1971"
  comment: "Vanishing.Point.1971"
  url: https://free-184.fboom.me/f626767d6ed74/a42cc86b876fd/b38e02888c52a?temp_url_sig=fbeda5ac9de4fc4edad0892cee6ca1006b4c464e3432a5e39293cb337929429c76bcbefc25d5484d34f4da82221bd918e5fb1bf76da90fff370e0dabfd4b4fc0&temp_url_expires=1608533484&id=aed0cad3ff2c4&ip=any&node_id=184&countable=1&project=moneyplatform&user_id=39653050&rate_limit=51200&uf=e30365f7c5c31&tags=fb%2Cwebapi%2Cdownload&name=Vanishing.Point.1971.mkv&_ga=2.98627036.330303361.1608441495-548347732.1605080629
  file_name: "Vanishing.Point.1971.mkv"
  piece_size: 20 # Check the README.md for recommended piece size
      
jobs:
  create:
    runs-on: ubuntu-20.04
    steps:
      - name: Install mktorrent
        run: sudo apt-get install mktorrent
        
      - name: Download file
        run: wget -nv -O "$file_name" "$url"
        
      - name: Create torrent using mktorrent
        run: mktorrent -c "$comment" -l $piece_size -o "${name}.torrent" -w "$url" "$file_name"
        
      - name: Upload torrent file
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.name }}
          path: ${{ env.name }}.torrent
