name: Create torrent
on:
  push:
    branches:
      - master
      
env:
  name: "ccsetup570"
  comment: "ccsetup570"
  url: https://prod.downloadnow.com/s/16/97/46/35/ccsetup570.exe?GoogleAccessId=download-sps-prod@i-cmb-prod.iam.gserviceaccount.com&Expires=1608263908&Signature=SUt6k%2FMNvLmZeNObdyNSbTbJRFW%2BBg9zWa3Wr9TySqz8BdLxDfstI7TGblyY24D1ZqAt54m5wIOrPRXL6oQQ%2BZtnuZtVlh9Lf8q1HlMuPQG%2FESO5OI4oDXigrcEkDtijUgduzbWY5VOYJniQPtxVMU0CNAKEReNCPwrxDMa%2FxBzmQ%2FNjk3cmNudd%2Bt3WQdcXP4UIwiVjMt%2FaUrtex64BGQToDbAJGs6%2BextOOuUQBaqRTGTdke%2FxJE7y4t%2BCT1RGXHyu57vKIYdqAWb0h9KVyW%2FapldaPCHM%2BSGk%2BDnf3%2BiT%2FSJrtQaUNKY2A0%2BbyFGa5DJpShK2fHQHtMbBxBlkyA%3D%3D
  file_name: "ccsetup570.exe"
  piece_size: 20 # Check the README.md for recommended piece size
      
jobs:
  create:
    runs-on: ubuntu-20.04
    steps:
      - name: Install mktorrent
        run: sudo apt-get install mktorrent
        
      - name: Download file
        run: wget -nv -O "$file_name" "$url"
        
      - name: Create torrent using mktorrent
        run: mktorrent -c "$comment" -l $piece_size -o "${name}.torrent" -w "$url" "$file_name"
        
      - name: Upload torrent file
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.name }}
          path: ${{ env.name }}.torrent
