name: Create torrent
on:
  push:
    branches:
      - master
      
env:
  name: "Willy Wonka & the Chocolate Factory (1971)"
  comment: "Willy Wonka & the Chocolate Factory (1971)"
  url: https://dlsv6.sonicbit.net/dl/zip2/U2xrMCtjdE9ta1RkcWNyYkVVVHNpODdVUWJMdE1tRWZHbEgwMytkSk9VYXA0UnpINkd5RWhhQnZhamxrelZIU1ZWdHY0T01FVVR5NGU5ejc4b3lWdFE9PQ==/506D61C50F8275E10DC63B25D3C5C2A7D1A778D7/Willy%20Wonka%20&%20the%20Chocolate%20Factory%20(1971)%201080p.zip
  file_name: "Willy Wonka & the Chocolate Factory (1971) [1080p].zip"
  piece_size: 20 # Check the README.md for recommended piece size
      
jobs:
  create:
    runs-on: ubuntu-20.04
    steps:
      - name: Install mktorrent
        run: sudo apt-get install mktorrent
        
      - name: Download file
        run: wget -nv -O "$file_name" "$url"
        
      - name: Create torrent using mktorrent
        run: mktorrent -c "$comment" -l $piece_size -o "${name}.torrent" -w "$url" "$file_name"
        
      - name: Upload torrent file
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.name }}
          path: ${{ env.name }}.torrent
