name: Create torrent
on:
  push:
    branches:
      - master
      
env:
  name: "Two.Mules.For.Sister.Sara.1970.1080p.BluRay.x264"
  comment: "Two.Mules.For.Sister.Sara.1970.1080p.BluRay.x264"
  url: https://nl21.seedr.cc/ff_get/803905604/Two.Mules.For.Sister.Sara.1970.1080p.BluRay.x264-[YTS.AG].mp4?st=DTYx9SczGmRRcHxNXIpNaQ&e=1607968622
  file_name: "Two.Mules.For.Sister.Sara.1970.1080p.BluRay.x264-[YTS.AG].mp4"
  piece_size: 20 # Check the README.md for recommended piece size
      
jobs:
  create:
    runs-on: ubuntu-20.04
    steps:
      - name: Install mktorrent
        run: sudo apt-get install mktorrent
        
      - name: Download file
        run: wget -nv -O "$file_name" "$url"
        
      - name: Create torrent using mktorrent
        run: mktorrent -c "$comment" -l $piece_size -o "${name}.torrent" -w "$url" "$file_name"
        
      - name: Upload torrent file
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.name }}
          path: ${{ env.name }}.torrent
