name: Create torrent
on:
  push:
    branches:
      - master
      
env:
  name: "Au Pair Girls (1972)"
  comment: "Au Pair Girls (1972)"
  url: https://dlsv6.sonicbit.net/dl/zip2/S29Jako1QWJRYXRPOG9vczRUdkRFTndXZ09wUXVDRzNKckc2aU5COFlaMUNlVUVDcmgyUVRQaDM0RHl6eUx0aW1FdXVwck5ERlFDSEhBbVZkQ0hacHc9PQ==/0F7FE004750CCA1A373BA4DFC148F893C150CB2C/Au%20Pair%20Girls%20(1972)%201080p%20[BluRay]%20[YTS.MX].zip
  file_name: "Au Pair Girls (1972) [1080p] [BluRay] [YTS.MX].zip"
  piece_size: 20 # Check the README.md for recommended piece size
      
jobs:
  create:
    runs-on: ubuntu-20.04
    steps:
      - name: Install mktorrent
        run: sudo apt-get install mktorrent
        
      - name: Download file
        run: wget -nv -O "$file_name" "$url"
        
      - name: Create torrent using mktorrent
        run: mktorrent -c "$comment" -l $piece_size -o "${name}.torrent" -w "$url" "$file_name"
        
      - name: Upload torrent file
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.name }}
          path: ${{ env.name }}.torrent
