name: Create torrent
on:
  push:
    branches:
      - master
      
env:
  name: "The.Dunwich.Horror.1970.720p.BluRay.x264"
  comment: "The.Dunwich.Horror.1970.720p.BluRay.x264"
  url: https://dlsv6.sonicbit.net/file/dl2/TXQ2UHNNQzBZWjdYdk5VbFg4eEhjUFZFTXdKclZSak9BYWc1R1k2MTJTeDJQakJhWVFWSUFZWGpEeWRleHhBT080TFY5NTFzRExYWm1DZlgzME8vVGxuVVRLNmM3TktMR3VUUzducExvWWpPb3NYaWx1VzF5Tmx3Q1pmU050cGtmUG9oZmswd1FRVzA2b1FZclZUcjkwUGZxR1o1QWM5SVoyNWJZL2JwVHFBQnZORDlQVTBtRStVVUxGYk9PcW8x/The.Dunwich.Horror.1970.720p.BluRay.x264-[YTS.AG].mp4
  file_name: "The.Dunwich.Horror.1970.720p.BluRay.x264-[YTS.AG].mp4"
  piece_size: 20 # Check the README.md for recommended piece size
      
jobs:
  create:
    runs-on: ubuntu-20.04
    steps:
      - name: Install mktorrent
        run: sudo apt-get install mktorrent
        
      - name: Download file
        run: wget -nv -O "$file_name" "$url"
        
      - name: Create torrent using mktorrent
        run: mktorrent -c "$comment" -l $piece_size -o "${name}.torrent" -w "$url" "$file_name"
        
      - name: Upload torrent file
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.name }}
          path: ${{ env.name }}.torrent
