name: Create torrent
on:
  push:
    branches:
      - master
      
env:
  name: "Grave Of The Vampire (1972)"
  comment: "Grave Of The Vampire (1972)"
  url: https://dlsv6.sonicbit.net/dl/zip2/WmVRRVg0SW9od2JVdGNhTHllRWplSzhyaXRQVUV2T09HZWx3N3JRTEU2MUg3ZVZYL3lOYjZnUnpsZkY5bDNkeGkxUWJJK1JsTytyVk04cm9hV1RYU2cxODdlYnpYMGhMZ0FOMHZ2N0tUVGc9/FF8BD5880D15332CFE00DBC04BF2FCFA1D5EAB5D/Grave%20Of%20The%20Vampire%20(1972)%201080p%20[BluRay]%20[YTS.MX].zip
  file_name: "Grave Of The Vampire (1972) [1080p] [BluRay] [YTS.MX].zip"
  piece_size: 20 # Check the README.md for recommended piece size
      
jobs:
  create:
    runs-on: ubuntu-20.04
    steps:
      - name: Install mktorrent
        run: sudo apt-get install mktorrent
        
      - name: Download file
        run: wget -nv -O "$file_name" "$url"
        
      - name: Create torrent using mktorrent
        run: mktorrent -c "$comment" -l $piece_size -o "${name}.torrent" -w "$url" "$file_name"
        
      - name: Upload torrent file
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.name }}
          path: ${{ env.name }}.torrent
