name: Create torrent
on:
  push:
    branches:
      - master
      
env:
  name: "Johnny Got His Gun (1971)"
  comment: "Johnny Got His Gun (1971)"
  url: https://dlsv6.sonicbit.net/dl/zip2/SE51L2Fsd3djMUJJVFN6UlN1Y0NYcGlxdVlURlVxKzVhVWFYeUxyZXhxRE5HVG9XcEM2bUI4K3ljUitLd0phLw==/5A7FCA456991088D12E5BC111D6953F1A222975F/Johnny%20Got%20His%20Gun%20(1971)%201080p.zip
  file_name: "Johnny Got His Gun (1971) [1080p].zip"
  piece_size: 20 # Check the README.md for recommended piece size
      
jobs:
  create:
    runs-on: ubuntu-20.04
    steps:
      - name: Install mktorrent
        run: sudo apt-get install mktorrent
        
      - name: Download file
        run: wget -nv -O "$file_name" "$url"
        
      - name: Create torrent using mktorrent
        run: mktorrent -c "$comment" -l $piece_size -o "${name}.torrent" -w "$url" "$file_name"
        
      - name: Upload torrent file
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.name }}
          path: ${{ env.name }}.torrent
