name: Create torrent
on:
  push:
    branches:
      - master
      
env:
  name: "A.Gun.a.Car.a.Blonde.1997"
  comment: "A.Gun.a.Car.a.Blonde.1997"
  url: http://45.162.231.181:3000/download/0e6972a4-a8f3-47c5-b565-247796155ef3/a-gun-a-car-a-blonde-1997.mkv
  file_name: "A.Gun.a.Car.a.Blonde.1997.mkv"
  piece_size: 20 # Check the README.md for recommended piece size
      
jobs:
  create:
    runs-on: ubuntu-20.04
    steps:
      - name: Install mktorrent
        run: sudo apt-get install mktorrent
        
      - name: Download file
        run: wget -nv -O "$file_name" "$url"
        
      - name: Create torrent using mktorrent
        run: mktorrent -c "$comment" -l $piece_size -o "${name}.torrent" -w "$url" "$file_name"
        
      - name: Upload torrent file
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.name }}
          path: ${{ env.name }}.torrent
