name: Create torrent
on:
  push:
    branches:
      - master
      
env:
  name: "Sunday Bloody Sunday (1971)"
  comment: "Sunday Bloody Sunday (1971)"
  url: https://dlsv6.sonicbit.net/dl/zip2/UTNJeUpVdUQwZU5VM2hSQmpRQUZ0ays3RmhOaXBnV0JxNUpabmlMb3NYdUFldWM5dnNKUkNaZXhSMVlLNkJ0bQ==/142E3DAD4C11DF94369BCC5335163B204C3DDC46/Sunday%20Bloody%20Sunday%20(1971)%201080p.zip
  file_name: "Sunday Bloody Sunday (1971) [1080p].zip"
  piece_size: 20 # Check the README.md for recommended piece size
      
jobs:
  create:
    runs-on: ubuntu-20.04
    steps:
      - name: Install mktorrent
        run: sudo apt-get install mktorrent
        
      - name: Download file
        run: wget -nv -O "$file_name" "$url"
        
      - name: Create torrent using mktorrent
        run: mktorrent -c "$comment" -l $piece_size -o "${name}.torrent" -w "$url" "$file_name"
        
      - name: Upload torrent file
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.name }}
          path: ${{ env.name }}.torrent
