name: Create torrent
on:
  push:
    branches:
      - master
      
env:
  name: "Sweet Sugar (1972)"
  comment: "Sweet Sugar (1972)"
  url: https://dlsv6.sonicbit.net/dl/zip2/N2FORWlpb0YwclZrdy9FQUx2MGRqNU1zdTgvL1FnbmF3OVFXQkZmNzVUZzhuSUdRSERnb0hGdXB6UWdsemZVYzNhTGFDaDlHYVFwSWFJck9qTHl5RHc9PQ==/38694E1F3C4620C0205EFFDA2C627F2B96990B15/Sweet%20Sugar%20(1972)%20BluRay%20[1080p]%20[YTS.LT].zip
  file_name: "Sweet Sugar (1972) [BluRay] [1080p] [YTS.LT].zip"
  piece_size: 20 # Check the README.md for recommended piece size
      
jobs:
  create:
    runs-on: ubuntu-20.04
    steps:
      - name: Install mktorrent
        run: sudo apt-get install mktorrent
        
      - name: Download file
        run: wget -nv -O "$file_name" "$url"
        
      - name: Create torrent using mktorrent
        run: mktorrent -c "$comment" -l $piece_size -o "${name}.torrent" -w "$url" "$file_name"
        
      - name: Upload torrent file
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.name }}
          path: ${{ env.name }}.torrent
