name: Create torrent
on:
  push:
    branches:
      - master
      
env:
  name: "Big Tit Massage 3"
  comment: "Big Tit Massage 3"
  url: https://RJB1981:RJB7581@claudia-marie.com/members/content//upload/030320bigtitmassage3/720p/030320bigtitmassage3.mp4
  file_name: "Big Tit Massage 3.mp4"
  piece_size: 20 # Check the README.md for recommended piece size
      
jobs:
  create:
    runs-on: ubuntu-20.04
    steps:
      - name: Install mktorrent
        run: sudo apt-get install mktorrent
        
      - name: Download file
        run: wget -nv -O "$file_name" "$url"
        
      - name: Create torrent using mktorrent
        run: mktorrent -c "$comment" -l $piece_size -o "${name}.torrent" -w "$url" "$file_name"
        
      - name: Upload torrent file
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.name }}
          path: ${{ env.name }}.torrent
