name: Create torrent
on:
  push:
    branches:
      - master
      
env:
  name: "A.Wing.and.a.Prayer.1998"
  comment: "A.Wing.and.a.Prayer.1998"
  url: http://45.162.231.181:3000/download/7f46a8ba-2c89-4c86-a984-2c811475e120/a-wing-and-a-prayer-1998.mkv
  file_name: "A.Wing.and.a.Prayer.1998.mkv"
  piece_size: 20 # Check the README.md for recommended piece size
      
jobs:
  create:
    runs-on: ubuntu-20.04
    steps:
      - name: Install mktorrent
        run: sudo apt-get install mktorrent
        
      - name: Download file
        run: wget -nv -O "$file_name" "$url"
        
      - name: Create torrent using mktorrent
        run: mktorrent -c "$comment" -l $piece_size -o "${name}.torrent" -w "$url" "$file_name"
        
      - name: Upload torrent file
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.name }}
          path: ${{ env.name }}.torrent
