name: Create torrent
on:
  push:
    branches:
      - master
      
env:
  name: "For.Love.or.Money.1993"
  comment: "For.Love.or.Money.1993"
  url: http://45.162.231.181:3000/download/5f2c352b-cf7f-4ea8-bf3f-e9e27e202633/for-love-or-money-1993.mkv
  file_name: "For.Love.or.Money.1993.mkv"
  piece_size: 20 # Check the README.md for recommended piece size
      
jobs:
  create:
    runs-on: ubuntu-20.04
    steps:
      - name: Install mktorrent
        run: sudo apt-get install mktorrent
        
      - name: Download file
        run: wget -nv -O "$file_name" "$url"
        
      - name: Create torrent using mktorrent
        run: mktorrent -c "$comment" -l $piece_size -o "${name}.torrent" -w "$url" "$file_name"
        
      - name: Upload torrent file
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.name }}
          path: ${{ env.name }}.torrent
