name: Create torrent
on:
  push:
    branches:
      - master
      
env:
  name: "Bedknobs and Broomsticks (1971)"
  comment: "Bedknobs and Broomsticks (1971)"
  url: https://dlsv6.sonicbit.net/dl/zip2/ditVSUZmclZjeFl3ZnJXSUVkT3hNVUVxZEhlQ2NIUWZtRlM2TnVWMC9ZbVMzazBZOUtHY2wvL0E4eUtRdThvS00zWDkzTTFBd1cwNWh1RVRVMER3NEE9PQ==/8A23DB068C1A80699517C73B07024286D7C8B387/Bedknobs%20and%20Broomsticks%20(1971)%201080p.zip
  file_name: "Bedknobs and Broomsticks (1971) [1080p].zip"
  piece_size: 20 # Check the README.md for recommended piece size
      
jobs:
  create:
    runs-on: ubuntu-20.04
    steps:
      - name: Install mktorrent
        run: sudo apt-get install mktorrent
        
      - name: Download file
        run: wget -nv -O "$file_name" "$url"
        
      - name: Create torrent using mktorrent
        run: mktorrent -c "$comment" -l $piece_size -o "${name}.torrent" -w "$url" "$file_name"
        
      - name: Upload torrent file
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.name }}
          path: ${{ env.name }}.torrent
