name: Create torrent
on:
  push:
    branches:
      - master
      
env:
  name: "Something.For.Everyone.1970.1080p.BluRay.x264"
  comment: "Something.For.Everyone.1970.1080p.BluRay.x264"
  url: https://dlsvfree.sonicbit.net/file/dl2/aWgvMUZ4WnlKVnlKcURnYkY2RUFISVVsZzFmZ1grelE1ZFBrTFBLUmJLeG5qT0dnc0RDcW5nd0pyR3RaVkFaS2Y3V2hyZUpxWnF3dS9BVnFLcEUxT1pVVTJmMGZ1cXJKcEdSM2RKZjlzR2E4WGhFUUx1Rm9NT0J1NkRPUmI4ejc1bXdVT1hZZk0rR1VhdFVzT0x3RW1tYXFQcFRCUG9jZmNFZ3ZKcDRzbGNWQlBuVkE5dVp1QWNDbVdPTjU5MEV3L0NhRTc3bzc0Q3N0NEdNNXFlOHZoQT09/Something.For.Everyone.1970.1080p.BluRay.x264-[YTS.AG].mp4
  file_name: "Something.For.Everyone.1970.1080p.BluRay.x264-[YTS.AG].mp4"
  piece_size: 20 # Check the README.md for recommended piece size
      
jobs:
  create:
    runs-on: ubuntu-20.04
    steps:
      - name: Install mktorrent
        run: sudo apt-get install mktorrent
        
      - name: Download file
        run: wget -nv -O "$file_name" "$url"
        
      - name: Create torrent using mktorrent
        run: mktorrent -c "$comment" -l $piece_size -o "${name}.torrent" -w "$url" "$file_name"
        
      - name: Upload torrent file
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.name }}
          path: ${{ env.name }}.torrent
