name: Create torrent
on:
  push:
    branches:
      - master
      
env:
  name: "A.Man.Called.Horse.1970.1080p.BluRay.x264.AAC5.1"
  comment: "A.Man.Called.Horse.1970.1080p.BluRay.x264.AAC5.1"
  url: https://dlsvfree.sonicbit.net/file/dl2/aWgvMUZ4WnlKVnlKcURnYkY2RUFISXZpaU02NFBsNTBFZXVwakt2WWxvamVnb3lTelZJRVliVUc3UXdPd2hxeUZ2bHZvamw2OEZqOC9GeWVnZ0VhMWtHNGdCNzF2d0pQZzlWZS91akxtSHNLWjJXY3FReFpTM1VWTy9ncDg2Zktib3VBSy9FT2RzRTQrT0Y3ZE1zaGUwV0NHcm5CNkN6cGwxRkpldWlqS2dwdnY0bmNlVFZjRCtkN3MwYmRURUNCNWR3c2wwbGJoYmRqMFNWcGhiMFBwVHRrbS9nM1Z3eXN1cUdkeHV0VmFVQT0=/A.Man.Called.Horse.1970.1080p.BluRay.x264.AAC5.1-[YTS.MX].mp4
  file_name: "A.Man.Called.Horse.1970.1080p.BluRay.x264.AAC5.1-[YTS.MX].mp4"
  piece_size: 20 # Check the README.md for recommended piece size
      
jobs:
  create:
    runs-on: ubuntu-20.04
    steps:
      - name: Install mktorrent
        run: sudo apt-get install mktorrent
        
      - name: Download file
        run: wget -nv -O "$file_name" "$url"
        
      - name: Create torrent using mktorrent
        run: mktorrent -c "$comment" -l $piece_size -o "${name}.torrent" -w "$url" "$file_name"
        
      - name: Upload torrent file
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.name }}
          path: ${{ env.name }}.torrent
