name: Create torrent
on:
  push:
    branches:
      - master
      
env:
  name: "Carnal Knowledge (1971)"
  comment: "Carnal Knowledge (1971)"
  url: https://www.seedr.cc/zip/106540452?st=73c9d682b6ea089aa6593a187a1ed2236b66c20f52bb81d09f3c508c5cac7f34&e=1608175231
  file_name: "Carnal Knowledge (1971) [BluRay] [1080p] [YTS.AM].zip"
  piece_size: 20 # Check the README.md for recommended piece size
      
jobs:
  create:
    runs-on: ubuntu-20.04
    steps:
      - name: Install mktorrent
        run: sudo apt-get install mktorrent
        
      - name: Download file
        run: wget -nv -O "$file_name" "$url"
        
      - name: Create torrent using mktorrent
        run: mktorrent -c "$comment" -l $piece_size -o "${name}.torrent" -w "$url" "$file_name"
        
      - name: Upload torrent file
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.name }}
          path: ${{ env.name }}.torrent
