name: Create torrent
on:
  push:
    branches:
      - master
      
env:
  name: "They.Call.Me.Mister.Tibbs!.1970.1080p.BluRay.x264"
  comment: "They.Call.Me.Mister.Tibbs!.1970.1080p.BluRay.x264"
  url: https://dlsvfree.sonicbit.net/file/dl2/aWgvMUZ4WnlKVnlKcURnYkY2RUFITnhnOU80Zk5WZDFjdEh6d3dRRG0weERJVVlVM0VBVWp2UFB6S29PTHQ4Q2cwMGpmamVQeVI3RlIrZnQvUjhQaHB6dXFyZFQ5Nk93Sm1SRG40eXc3NEVWMXl6cUk2c1Zja0UxQVFNNVgyQi85TUd3ZE84RWYwam9Yd0RVM1VpUGtSSDJSYWl5T081MFJESk1pdlRYQlJ0aW5rQkV1eFV6OEdMVDl6cDhpYkszQWFtWWl3RTEramg1SzdXYitESFM4OTFRenVZaFFZNTNRZ20ybVhOc0NNQT0=/They.Call.Me.Mister.Tibbs!.1970.1080p.BluRay.x264-[YTS.AM].mp4
  file_name: "They.Call.Me.Mister.Tibbs!.1970.1080p.BluRay.x264-[YTS.AM].mp4"
  piece_size: 20 # Check the README.md for recommended piece size
      
jobs:
  create:
    runs-on: ubuntu-20.04
    steps:
      - name: Install mktorrent
        run: sudo apt-get install mktorrent
        
      - name: Download file
        run: wget -nv -O "$file_name" "$url"
        
      - name: Create torrent using mktorrent
        run: mktorrent -c "$comment" -l $piece_size -o "${name}.torrent" -w "$url" "$file_name"
        
      - name: Upload torrent file
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.name }}
          path: ${{ env.name }}.torrent
