name: Create torrent
on:
  push:
    branches:
      - master
      
env:
  name: "Le.Mans.1971.1080p.BluRay.x264"
  comment: "Le.Mans.1971.1080p.BluRay.x264"
  url: https://dlsv6.sonicbit.net/file/dl2/TXQ2UHNNQzBZWjdYdk5VbFg4eEhjUFZFTXdKclZSak9BYWc1R1k2MTJTd0VkR2NpSXN3NXFyOVNvN3dUSkpFNFd4aUJxYjNoeDduOFBQV21ScW9xeHYza3Q1bjljUEdZVm5xRGZvS2ZZN1JLR3BUZ2hkeG5PT0FZWk5VZjNGTkQwNzZPM2ZiMHRldDVYWDNCVkptQlM2WXQrL09LTGl3NVBXZERmRG1vVHFKOHMrblkwbXNxNHdFOG5Kd2FpMWt4/Le.Mans.1971.1080p.BluRay.x264-[YTS.AM].mp4
  file_name: "Le.Mans.1971.1080p.BluRay.x264-[YTS.AM].mp4"
  piece_size: 20 # Check the README.md for recommended piece size
      
jobs:
  create:
    runs-on: ubuntu-20.04
    steps:
      - name: Install mktorrent
        run: sudo apt-get install mktorrent
        
      - name: Download file
        run: wget -nv -O "$file_name" "$url"
        
      - name: Create torrent using mktorrent
        run: mktorrent -c "$comment" -l $piece_size -o "${name}.torrent" -w "$url" "$file_name"
        
      - name: Upload torrent file
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.name }}
          path: ${{ env.name }}.torrent
