name: Create torrent
on:
  push:
    branches:
      - master
      
env:
  name: "The Brotherhood Of Satan (1971)"
  comment: "The Brotherhood Of Satan (1971)"
  url: https://dlsv6.sonicbit.net/dl/zip2/Yzl4TmY0a0pqbDJMYzZ6QkVmckRGdGU3Z3RlMGtuZzNMR2ljZDVBdytud3IyQzVkbU8wOFBVWDVGY0JiaTJWWUdzZ3J0Mm1lbVJaOTAwTndJYnFKSEowWXBrZy8xSVZJVnM5TjY0NmZzdUU9/BF2AD27220C72DB2235CC36239265B3CDC24A1BB/The%20Brotherhood%20Of%20Satan%20(1971)%20BluRay%20[1080p]%20[YTS.AM].zip
  file_name: "The Brotherhood Of Satan (1971) [BluRay] [1080p] [YTS.AM].zip"
  piece_size: 20 # Check the README.md for recommended piece size
      
jobs:
  create:
    runs-on: ubuntu-20.04
    steps:
      - name: Install mktorrent
        run: sudo apt-get install mktorrent
        
      - name: Download file
        run: wget -nv -O "$file_name" "$url"
        
      - name: Create torrent using mktorrent
        run: mktorrent -c "$comment" -l $piece_size -o "${name}.torrent" -w "$url" "$file_name"
        
      - name: Upload torrent file
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.name }}
          path: ${{ env.name }}.torrent
