name: Create torrent
on:
  push:
    branches:
      - master
      
env:
  name: "The.Touch.1971.1080p.BluRay.x264"
  comment: "The.Touch.1971.1080p.BluRay.x264"
  url: https://dlsv6.sonicbit.net/file/dl2/TXQ2UHNNQzBZWjdYdk5VbFg4eEhjUFZFTXdKclZSak9BYWc1R1k2MTJTelUvZ1l3cFFkQzRBTjhGOUg0N1BRVzNSM09USVgzcGNwVlg3T1lyM2JmMFJHb0ZmV3kxM1Y0K2JLMVUwZ2J3cStkdHh4MzNSeTQvT1YwM3NjYStMK2ExeXIzbElPRXVqQTVlOUtqQ2RDQ3dxNlcyYy9xWXh0cFQ5YWN3Y00vUG4yZjJMTTBENjYzSElIUlpMMHJYenVM/The.Touch.1971.1080p.BluRay.x264-[YTS.LT].mp4
  file_name: "The.Touch.1971.1080p.BluRay.x264-[YTS.LT].mp4"
  piece_size: 20 # Check the README.md for recommended piece size
      
jobs:
  create:
    runs-on: ubuntu-20.04
    steps:
      - name: Install mktorrent
        run: sudo apt-get install mktorrent
        
      - name: Download file
        run: wget -nv -O "$file_name" "$url"
        
      - name: Create torrent using mktorrent
        run: mktorrent -c "$comment" -l $piece_size -o "${name}.torrent" -w "$url" "$file_name"
        
      - name: Upload torrent file
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.name }}
          path: ${{ env.name }}.torrent
