name: Create torrent
on:
  push:
    branches:
      - master
      
env:
  name: "Harold And Maude (1971)"
  comment: "Harold And Maude (1971)"
  url: https://de14.seedr.cc/get_zip_ngen/106548688/Harold%20And%20Maude%20(1971)%20[BluRay]%20[1080p]%20[YTS.AM].zip?st=_RBYGEgMcG-whfrRUd_RsA&e=1608225198
  file_name: "Harold And Maude (1971) [BluRay] [1080p] [YTS.AM].zip"
  piece_size: 20 # Check the README.md for recommended piece size
      
jobs:
  create:
    runs-on: ubuntu-20.04
    steps:
      - name: Install mktorrent
        run: sudo apt-get install mktorrent
        
      - name: Download file
        run: wget -nv -O "$file_name" "$url"
        
      - name: Create torrent using mktorrent
        run: mktorrent -c "$comment" -l $piece_size -o "${name}.torrent" -w "$url" "$file_name"
        
      - name: Upload torrent file
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.name }}
          path: ${{ env.name }}.torrent
