name: Create torrent
on:
  push:
    branches:
      - master
      
env:
  name: "How.Do.I.Love.Thee.1970.1080p.BluRay.x264.AAC"
  comment: "How.Do.I.Love.Thee.1970.1080p.BluRay.x264.AAC"
  url: https://nl19.seedr.cc/ff_get/803744809/How.Do.I.Love.Thee.1970.1080p.BluRay.x264.AAC-[YTS.MX].mp4?st=4Umqyyk91DYfqh43WFp4Lw&e=1607955961
  file_name: "How.Do.I.Love.Thee.1970.1080p.BluRay.x264.AAC-[YTS.MX].mp4"
  piece_size: 20 # Check the README.md for recommended piece size
      
jobs:
  create:
    runs-on: ubuntu-20.04
    steps:
      - name: Install mktorrent
        run: sudo apt-get install mktorrent
        
      - name: Download file
        run: wget -nv -O "$file_name" "$url"
        
      - name: Create torrent using mktorrent
        run: mktorrent -c "$comment" -l $piece_size -o "${name}.torrent" -w "$url" "$file_name"
        
      - name: Upload torrent file
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.name }}
          path: ${{ env.name }}.torrent
