name: Create torrent
on:
  push:
    branches:
      - master
      
env:
  name: "Death In Venice (1971)"
  comment: "Death In Venice (1971)"
  url: https://dlsv6.sonicbit.net/dl/zip2/UVpFaGtMOTBMMVVrNGxud2RpQVdadXozbnROM01GZDl5bWhHZUFFRWhmKzV5N004eGN6MXN4RkFLZFVhRUpIa2dMMUh5TE8yWGVFdE1HZUNqKzhZV1E9PQ==/77771DFC2525245631291A766E95D6D30C6EDA01/Death%20In%20Venice%20(1971)%20BluRay%20[1080p]%20[YTS.AM].zip
  file_name: "Death In Venice (1971) [BluRay] [1080p] [YTS.AM].zip"
  piece_size: 20 # Check the README.md for recommended piece size
      
jobs:
  create:
    runs-on: ubuntu-20.04
    steps:
      - name: Install mktorrent
        run: sudo apt-get install mktorrent
        
      - name: Download file
        run: wget -nv -O "$file_name" "$url"
        
      - name: Create torrent using mktorrent
        run: mktorrent -c "$comment" -l $piece_size -o "${name}.torrent" -w "$url" "$file_name"
        
      - name: Upload torrent file
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.name }}
          path: ${{ env.name }}.torrent
