name: Create torrent
on:
  push:
    branches:
      - master
      
env:
  name: "Jo (1971)"
  comment: "Jo (1971)"
  url: https://dlsv6.sonicbit.net/dl/zip2/TGNBUzN5TnFDWnMzYzdWZjNCNjkwNEk5NHdwZXpCbEI1bEZwdDRoc3lCNXg0M1BTVnN5ZnRrQ2ZyR0lGaXN2Vg==/2BD70BD013F7C314DE887676EA8A3ED3A12E47FB/Jo%20(1971)%201080p%20[WEBRip]%20[YTS.MX].zip
  file_name: "Jo (1971) [1080p] [WEBRip] [YTS.MX].zip"
  piece_size: 20 # Check the README.md for recommended piece size
      
jobs:
  create:
    runs-on: ubuntu-20.04
    steps:
      - name: Install mktorrent
        run: sudo apt-get install mktorrent
        
      - name: Download file
        run: wget -nv -O "$file_name" "$url"
        
      - name: Create torrent using mktorrent
        run: mktorrent -c "$comment" -l $piece_size -o "${name}.torrent" -w "$url" "$file_name"
        
      - name: Upload torrent file
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.name }}
          path: ${{ env.name }}.torrent
