name: Create torrent
on:
  push:
    branches:
      - master
      
env:
  name: "The.Decameron.1971.1080p.BluRay.x264.AAC"
  comment: "The.Decameron.1971.1080p.BluRay.x264.AAC"
  url: https://dlsv6.sonicbit.net/file/dl2/TXQ2UHNNQzBZWjdYdk5VbFg4eEhjUFZFTXdKclZSak9BYWc1R1k2MTJTeSt2RmR0M1NjSllweUVMclQ3M2lGeEVCaDVOQTJLQ0Y2ZE1sanhScU0zdkFmMHJSdkIvNVBqTFk4ZDlrbFZEKzVnb1QwTUcrSEZCZlFmK3FMMWZueFZqKzVSNGdXeUg3ZlJsWGZsNEFCRllJbjZCWE9UK2VVd2RQaUxVUFgvbEhLZWFEa0p2ZXROdGdhZGJSTzFFYnIzT2pKTml2a0hSVjdyc0NpL29Sbko0UT09/The.Decameron.1971.1080p.BluRay.x264.AAC-[YTS.MX].mp4
  file_name: "The.Decameron.1971.1080p.BluRay.x264.AAC-[YTS.MX].mp4"
  piece_size: 20 # Check the README.md for recommended piece size
      
jobs:
  create:
    runs-on: ubuntu-20.04
    steps:
      - name: Install mktorrent
        run: sudo apt-get install mktorrent
        
      - name: Download file
        run: wget -nv -O "$file_name" "$url"
        
      - name: Create torrent using mktorrent
        run: mktorrent -c "$comment" -l $piece_size -o "${name}.torrent" -w "$url" "$file_name"
        
      - name: Upload torrent file
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.name }}
          path: ${{ env.name }}.torrent
