name: Create torrent
on:
  push:
    branches:
      - master
      
env:
  name: "James Bond Diamonds Are Forever (1971)"
  comment: "James Bond Diamonds Are Forever (1971)"
  url: https://dlsv6.sonicbit.net/dl/zip2/Y1pKWmNnQ0N4VEkySm9ZR2hiVTBtekVudVNWTWh4Vys3MnZCcWYvMC9lWWpWMmhiWm52N1ljRFVZbW1hcWZXcmgzQzZUclNBSjkzLzdEWXVsRlprdUE9PQ==/40D072D340B91121E3370BAA203A37344B9F1525/James%20Bond%20Diamonds%20Are%20Forever%20(1971).zip
  file_name: "James Bond Diamonds Are Forever (1971).zip"
  piece_size: 20 # Check the README.md for recommended piece size
      
jobs:
  create:
    runs-on: ubuntu-20.04
    steps:
      - name: Install mktorrent
        run: sudo apt-get install mktorrent
        
      - name: Download file
        run: wget -nv -O "$file_name" "$url"
        
      - name: Create torrent using mktorrent
        run: mktorrent -c "$comment" -l $piece_size -o "${name}.torrent" -w "$url" "$file_name"
        
      - name: Upload torrent file
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.name }}
          path: ${{ env.name }}.torrent
