name: Create torrent
on:
  push:
    branches:
      - master
      
env:
  name: "Rio.Lobo.1970.1080p.BluRay.x264.AAC5.1"
  comment: "Rio.Lobo.1970.1080p.BluRay.x264.AAC5.1"
  url: https://dlsvfree.sonicbit.net/file/dl2/aWgvMUZ4WnlKVnlKcURnYkY2RUFIQVNYcVdSTmJlL21yTkFsSm1VQmNOdjRPY0hReVVQazZXY2FDUjBVNmlta2dLSnZKL1M2MVBVdEpnZ081N1BZdkdaUEFSbUUyZnFKRlF1YUlnM3dMUTBrSFJGYWNlWXl1OUkxSFp6aHExbUc4T0NCL2pZQWxFcGhYQk9WRTRYNXRGd2xPZ3VhTWlPc2xFa1BIZmRjVzhVL1JDaXNFNG0xZUIwbFk5WTQvQktm/Rio.Lobo.1970.1080p.BluRay.x264.AAC5.1-[YTS.MX].mp4
  file_name: "Rio.Lobo.1970.1080p.BluRay.x264.AAC5.1-[YTS.MX].mp4"
  piece_size: 20 # Check the README.md for recommended piece size
      
jobs:
  create:
    runs-on: ubuntu-20.04
    steps:
      - name: Install mktorrent
        run: sudo apt-get install mktorrent
        
      - name: Download file
        run: wget -nv -O "$file_name" "$url"
        
      - name: Create torrent using mktorrent
        run: mktorrent -c "$comment" -l $piece_size -o "${name}.torrent" -w "$url" "$file_name"
        
      - name: Upload torrent file
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.name }}
          path: ${{ env.name }}.torrent
