name: Create torrent
on:
  push:
    branches:
      - master
      
env:
  name: "Struggle In Italy (1971)"
  comment: "Struggle In Italy (1971)"
  url: https://dlsv6.sonicbit.net/dl/zip2/bGVhVmpNb09nRWNxa0FGZi8xYk9TNUdFSnVSeHRzam1iMENIQUcrZXYzOWZNVkhLZUJwVWFMS3p1WlZqdW40Nlc1eXdhK0JhaW40VDdGY3EzaHZ0a1E9PQ==/9024B477A57C09F0B5449D8AC59C104B33656E5A/Struggle%20In%20Italy%20(1971)%20BluRay%20[1080p]%20[YTS.AM].zip
  file_name: "Struggle In Italy (1971) [BluRay] [1080p] [YTS.AM].zip"
  piece_size: 20 # Check the README.md for recommended piece size
      
jobs:
  create:
    runs-on: ubuntu-20.04
    steps:
      - name: Install mktorrent
        run: sudo apt-get install mktorrent
        
      - name: Download file
        run: wget -nv -O "$file_name" "$url"
        
      - name: Create torrent using mktorrent
        run: mktorrent -c "$comment" -l $piece_size -o "${name}.torrent" -w "$url" "$file_name"
        
      - name: Upload torrent file
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.name }}
          path: ${{ env.name }}.torrent
