name: Create torrent
on:
  push:
    branches:
      - master
      
env:
  name: "The.Panther.Squad.1984"
  comment: "The.Panther.Squad.1984"
  url: http://45.162.231.181:3000/download/56c75787-b1a3-46d2-8af2-5a97e2971cf1/the-panther-squad-1984.mkv
  file_name: "The.Panther.Squad.1984.mkv"
  piece_size: 20 # Check the README.md for recommended piece size
      
jobs:
  create:
    runs-on: ubuntu-20.04
    steps:
      - name: Install mktorrent
        run: sudo apt-get install mktorrent
        
      - name: Download file
        run: wget -nv -O "$file_name" "$url"
        
      - name: Create torrent using mktorrent
        run: mktorrent -c "$comment" -l $piece_size -o "${name}.torrent" -w "$url" "$file_name"
        
      - name: Upload torrent file
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.name }}
          path: ${{ env.name }}.torrent
