name: Create torrent
on:
  push:
    branches:
      - master
      
env:
  name: "This Stuff'll Kill Ya! (1971)"
  comment: "This Stuff'll Kill Ya! (1971)"
  url: https://dlsv6.sonicbit.net/dl/zip2/cmxQWVdod3Q5Z0cvbkYzTGxHQXhNYThDNzdOaUNLdENqNldOdnpZc0gxSUkwZUlRbGkxMTlXdFArS1krbzl0SUhrbHBUV1Q3a0dWZ3ZzTDA1cWhlM1E9PQ==/3C2A78686EA1EC9D0BC1BCEDAA2C2C73A8D4057C/This%20Stuff'll%20Kill%20Ya!%20(1971)%201080p%20[YTS.AG].zip
  file_name: "This Stuff'll Kill Ya! (1971) [1080p] [YTS.AG].zip"
  piece_size: 20 # Check the README.md for recommended piece size
      
jobs:
  create:
    runs-on: ubuntu-20.04
    steps:
      - name: Install mktorrent
        run: sudo apt-get install mktorrent
        
      - name: Download file
        run: wget -nv -O "$file_name" "$url"
        
      - name: Create torrent using mktorrent
        run: mktorrent -c "$comment" -l $piece_size -o "${name}.torrent" -w "$url" "$file_name"
        
      - name: Upload torrent file
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.name }}
          path: ${{ env.name }}.torrent
