name: Create torrent
on:
  push:
    branches:
      - master
      
env:
  name: "Mister.Frost.1990"
  comment: "Mister.Frost.1990"
  url: http://45.162.231.181:3000/download/f8f5cef8-2284-479f-8c0d-ce3d52b62a9b/mister-frost-1990.mkv
  file_name: "Mister.Frost.1990.mkv"
  piece_size: 20 # Check the README.md for recommended piece size
      
jobs:
  create:
    runs-on: ubuntu-20.04
    steps:
      - name: Install mktorrent
        run: sudo apt-get install mktorrent
        
      - name: Download file
        run: wget -nv -O "$file_name" "$url"
        
      - name: Create torrent using mktorrent
        run: mktorrent -c "$comment" -l $piece_size -o "${name}.torrent" -w "$url" "$file_name"
        
      - name: Upload torrent file
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.name }}
          path: ${{ env.name }}.torrent
