name: Create torrent
on:
  push:
    branches:
      - master
      
env:
  name: "A.Touch.Of.Zen.1971.1080p.BluRay.x264"
  comment: "A.Touch.Of.Zen.1971.1080p.BluRay.x264"
  url: https://dlsv6.sonicbit.net/file/dl2/TXQ2UHNNQzBZWjdYdk5VbFg4eEhjUFZFTXdKclZSak9BYWc1R1k2MTJTeGN2WFQxRm1kSXlpZWtVVEljNU5rUnNhWDhXbjVzN1pCbmJJU2QrQytJZDliVUIxTDF6MHRrZmo0ei83cEh2V3BkLzcwNXpadlRQQlROUjlxLy9iRnZJdW9venhiOGhnOWp5UHBMQ1gwaEdxWkx1NUM4TytIS3NlQTI0aUJhZnVXemJlQUorQWo1Lyt4bXpMcWdnOXhQ/A.Touch.Of.Zen.1971.1080p.BluRay.x264-[YTS.LT].mp4
  file_name: "A.Touch.Of.Zen.1971.1080p.BluRay.x264-[YTS.LT].mp4"
  piece_size: 20 # Check the README.md for recommended piece size
      
jobs:
  create:
    runs-on: ubuntu-20.04
    steps:
      - name: Install mktorrent
        run: sudo apt-get install mktorrent
        
      - name: Download file
        run: wget -nv -O "$file_name" "$url"
        
      - name: Create torrent using mktorrent
        run: mktorrent -c "$comment" -l $piece_size -o "${name}.torrent" -w "$url" "$file_name"
        
      - name: Upload torrent file
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.name }}
          path: ${{ env.name }}.torrent
