name: Create torrent
on:
  push:
    branches:
      - master
      
env:
  name: "The.Warriors.1979"
  comment: "The.Warriors.1979"
  url: http://45.162.231.181:3000/download/191e326c-f999-4421-9bd3-288bcec1d6dd/the-warriors-1979.mkv
  file_name: "The.Warriors.1979.mkv"
  piece_size: 20 # Check the README.md for recommended piece size
      
jobs:
  create:
    runs-on: ubuntu-20.04
    steps:
      - name: Install mktorrent
        run: sudo apt-get install mktorrent
        
      - name: Download file
        run: wget -nv -O "$file_name" "$url"
        
      - name: Create torrent using mktorrent
        run: mktorrent -c "$comment" -l $piece_size -o "${name}.torrent" -w "$url" "$file_name"
        
      - name: Upload torrent file
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.name }}
          path: ${{ env.name }}.torrent
