name: Create torrent
on:
  push:
    branches:
      - master
      
env:
  name: "Figures.In.A.Landscape.1970.1080p.BluRay.x264"
  comment: "Figures.In.A.Landscape.1970.1080p.BluRay.x264"
  url: https://dlsvfree.sonicbit.net/file/dl2/aWgvMUZ4WnlKVnlKcURnYkY2RUFIS1NFME1vUlJsZzRpQ05qVk9OenZjdjRiZmtxdCtJUFFTMHBvekhZeHQ4YnRJcjV4KzN2YUx1cW9QWTBWcldJb0J0WGU3UDZzOW1VNDhKNHRUTkZ4V1pMTFhaNXRFOUtqY2gyQ25oVWxiVjVFUDJPYWUzaWdZdVZ6cW96VTJSSDNNZU1COTJacWp4SitIWmNwWjV4UmFCc0ZsTDZsNnVUV2plRjhGRDJhK0RMNXVUV2M2WUh3czNCT1RlSXJ5SGhZZz09/Figures.In.A.Landscape.1970.1080p.BluRay.x264-[YTS.AG].mp4
  file_name: "Figures.In.A.Landscape.1970.1080p.BluRay.x264-[YTS.AG].mp4"
  piece_size: 20 # Check the README.md for recommended piece size
      
jobs:
  create:
    runs-on: ubuntu-20.04
    steps:
      - name: Install mktorrent
        run: sudo apt-get install mktorrent
        
      - name: Download file
        run: wget -nv -O "$file_name" "$url"
        
      - name: Create torrent using mktorrent
        run: mktorrent -c "$comment" -l $piece_size -o "${name}.torrent" -w "$url" "$file_name"
        
      - name: Upload torrent file
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.name }}
          path: ${{ env.name }}.torrent
