name: Create torrent
on:
  push:
    branches:
      - master
      
env:
  name: "Beneath.the.Planet.of.the.Apes.1970.1080p.BrRip.x264"
  comment: "Beneath.the.Planet.of.the.Apes.1970.1080p.BrRip.x264"
  url: https://dlsv6.sonicbit.net/file/dl2/TXQ2UHNNQzBZWjdYdk5VbFg4eEhjUFZFTXdKclZSak9BYWc1R1k2MTJTejB0T3RwdWsvU1A2aStuajNMWGZ4UTg0QTMwbmJjWUI3Q0tnZitmaW5ZQytPT29jN2E2Q2xleEIwazFGeitidlBmb1ViTVErL0pTMTAwdzFpcmNDMGVheWV2VkdBTkt4RFRReXp3NjJnc09RZDlGdElUOFpmczc5akdmUGVZRUdScVpVdEJ4dk5XVUljdjVMdzZHK1ZaRGJKT0R1UjNDUkYyMzV2SnArejhGZz09/Beneath.the.Planet.of.the.Apes.1970.1080p.BrRip.x264.BOKUTOX.YIFY.mp4
  file_name: "Beneath.the.Planet.of.the.Apes.1970.1080p.BrRip.x264.BOKUTOX.YIFY.mp4"
  piece_size: 20 # Check the README.md for recommended piece size
      
jobs:
  create:
    runs-on: ubuntu-20.04
    steps:
      - name: Install mktorrent
        run: sudo apt-get install mktorrent
        
      - name: Download file
        run: wget -nv -O "$file_name" "$url"
        
      - name: Create torrent using mktorrent
        run: mktorrent -c "$comment" -l $piece_size -o "${name}.torrent" -w "$url" "$file_name"
        
      - name: Upload torrent file
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.name }}
          path: ${{ env.name }}.torrent
