name: Create torrent
on:
  push:
    branches:
      - master
      
env:
  name: "Blutjunge Verfuhrerinnen 3. Teil (1972)"
  comment: "Blutjunge Verfuhrerinnen 3. Teil (1972)"
  url: https://dlsv6.sonicbit.net/dl/zip2/dlo1djRzamRjcGt0SXNaUElJVm14Zk94dWxLaFB3NVBzV1pvd0plVGlNWm9vL2JlZXpWRFpUMkZySklQS3oyOHQ1aHA2RldWb05XYTFjWERENGZRR1JkQkF0OTROeldJVFBOVkZ4RkNuYXM9/6654A4320FFC8558C1E5EEE01A640B4B010FCB36/Blutjunge%20Verfuhrerinnen%203.%20Teil%20(1972)%201080p%20[BluRay]%20[YTS.MX].zip
  file_name: "Blutjunge Verfuhrerinnen 3. Teil (1972) [1080p] [BluRay] [YTS.MX].zip"
  piece_size: 20 # Check the README.md for recommended piece size
      
jobs:
  create:
    runs-on: ubuntu-20.04
    steps:
      - name: Install mktorrent
        run: sudo apt-get install mktorrent
        
      - name: Download file
        run: wget -nv -O "$file_name" "$url"
        
      - name: Create torrent using mktorrent
        run: mktorrent -c "$comment" -l $piece_size -o "${name}.torrent" -w "$url" "$file_name"
        
      - name: Upload torrent file
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.name }}
          path: ${{ env.name }}.torrent
