name: Create torrent
on:
  push:
    branches:
      - master
      
env:
  name: "Fiddler On The Roof (1971)"
  comment: "Fiddler On The Roof (1971)"
  url: https://dlsv6.sonicbit.net/dl/zip2/eDVNS2pwSzRmeTBGYm5mWmpRRzN4aXJzODU3bXpnUTRIVmd5clVPK01TNDkyNXBsNll2czl0Q1o2cnpQblAzT2VRbEowZ2ozb1lvdFF4emdtRU1KQWc9PQ==/86CA10D139D862E24D7A0592ECDD57A50EFE89E8/Fiddler%20On%20The%20Roof%20(1971)%201080p%20[YTS.AG].zip
  file_name: "Fiddler On The Roof (1971) [1080p] [YTS.AG].zip"
  piece_size: 20 # Check the README.md for recommended piece size
      
jobs:
  create:
    runs-on: ubuntu-20.04
    steps:
      - name: Install mktorrent
        run: sudo apt-get install mktorrent
        
      - name: Download file
        run: wget -nv -O "$file_name" "$url"
        
      - name: Create torrent using mktorrent
        run: mktorrent -c "$comment" -l $piece_size -o "${name}.torrent" -w "$url" "$file_name"
        
      - name: Upload torrent file
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.name }}
          path: ${{ env.name }}.torrent
