name: Create torrent
on:
  push:
    branches:
      - master
      
env:
  name: "Fist Of Fury (1972)"
  comment: "Fist Of Fury (1972)"
  url: https://dlsv6.sonicbit.net/dl/zip2/TjJ2ZXlTM1Bsb3YvS21oU2VFeTgxdWw4NmJ5M3ZtMEpkN2hqQ3RISUFKS3VqcnQ4dUEranhVRGFURGI2QjlzOTVWbWRDOGZnckgwbzcyOXpNSWRLdnc9PQ==/1B8150466C61FB2C36552632AF09F944705AEAA0/Fist%20Of%20Fury%20(1972)%20BluRay%20[1080p]%20[YTS.LT].zip
  file_name: "Fist Of Fury (1972) [BluRay] [1080p] [YTS.LT].zip"
  piece_size: 20 # Check the README.md for recommended piece size
      
jobs:
  create:
    runs-on: ubuntu-20.04
    steps:
      - name: Install mktorrent
        run: sudo apt-get install mktorrent
        
      - name: Download file
        run: wget -nv -O "$file_name" "$url"
        
      - name: Create torrent using mktorrent
        run: mktorrent -c "$comment" -l $piece_size -o "${name}.torrent" -w "$url" "$file_name"
        
      - name: Upload torrent file
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.name }}
          path: ${{ env.name }}.torrent
