name: Create torrent
on:
  push:
    branches:
      - master
      
env:
  name: "The.Expanse.S05E02.720p.WEB.x265"
  comment: "The.Expanse.S05E02.720p.WEB.x265"
  url: https://nl22.seedr.cc/ff_get/805571584/The.Expanse.S05E02.720p.WEB.x265-MiNX.mkv?st=0OLAJaR-DJeGyshpZ9G2Ag&e=1608194894
  file_name: "The.Expanse.S05E02.720p.WEB.x265-MiNX.mkv"
  piece_size: 20 # Check the README.md for recommended piece size
      
jobs:
  create:
    runs-on: ubuntu-20.04
    steps:
      - name: Install mktorrent
        run: sudo apt-get install mktorrent
        
      - name: Download file
        run: wget -nv -O "$file_name" "$url"
        
      - name: Create torrent using mktorrent
        run: mktorrent -c "$comment" -l $piece_size -o "${name}.torrent" -w "$url" "$file_name"
        
      - name: Upload torrent file
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.name }}
          path: ${{ env.name }}.torrent
