name: Create torrent
on:
  push:
    branches:
      - master
      
env:
  name: "NeXt.2020.S01E07.WEB.x264"
  comment: "NeXt.2020.S01E07.WEB.x264"
  url: https://dlsv6.sonicbit.net/file/dl2/TXQ2UHNNQzBZWjdYdk5VbFg4eEhjUFZFTXdKclZSak9BYWc1R1k2MTJTeWw1OXBROXVrS0c3TjFwQlF6ZWZsM0ZsMTBacVJNWmxBUno4S1lqUzVYTHg2OElLUmp6MUpKQXRwbEErNFVMNGd1RUhmZEY1RUxvSTNoNTNZd0g4SitwMEVoVURscXlJVzdMZGluR1ZXa3pWS3I3T1k2YnpBTTFaYzVBQ1JrZmlvPQ==/NeXt.2020.S01E07.WEB.x264-PHOENiX.mkv
  file_name: "NeXt.2020.S01E07.WEB.x264-PHOENiX.mkv"
  piece_size: 20 # Check the README.md for recommended piece size
      
jobs:
  create:
    runs-on: ubuntu-20.04
    steps:
      - name: Install mktorrent
        run: sudo apt-get install mktorrent
        
      - name: Download file
        run: wget -nv -O "$file_name" "$url"
        
      - name: Create torrent using mktorrent
        run: mktorrent -c "$comment" -l $piece_size -o "${name}.torrent" -w "$url" "$file_name"
        
      - name: Upload torrent file
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.name }}
          path: ${{ env.name }}.torrent
