name: Create torrent
on:
  push:
    branches:
      - master
      
env:
  name: "Whisper.Kill.1988"
  comment: "Whisper.Kill.1988"
  url: http://45.162.231.181:3000/download/40ef0fdc-845b-4148-b1a9-62bd4fe2fe03/whisper-kill-1988.mkv
  file_name: "Whisper.Kill.1988.mkv"
  piece_size: 20 # Check the README.md for recommended piece size
      
jobs:
  create:
    runs-on: ubuntu-20.04
    steps:
      - name: Install mktorrent
        run: sudo apt-get install mktorrent
        
      - name: Download file
        run: wget -nv -O "$file_name" "$url"
        
      - name: Create torrent using mktorrent
        run: mktorrent -c "$comment" -l $piece_size -o "${name}.torrent" -w "$url" "$file_name"
        
      - name: Upload torrent file
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.name }}
          path: ${{ env.name }}.torrent
