name: Create torrent
on:
  push:
    branches:
      - master
      
env:
  name: "Finders.Keepers.1984"
  comment: "Finders.Keepers.1984"
  url: http://45.162.231.181:3000/download/92bf4a18-8c8b-4edc-8d11-2be03c7d7ffd/finders-keepers-1984.mkv
  file_name: "Finders.Keepers.1984.mkv"
  piece_size: 20 # Check the README.md for recommended piece size
      
jobs:
  create:
    runs-on: ubuntu-20.04
    steps:
      - name: Install mktorrent
        run: sudo apt-get install mktorrent
        
      - name: Download file
        run: wget -nv -O "$file_name" "$url"
        
      - name: Create torrent using mktorrent
        run: mktorrent -c "$comment" -l $piece_size -o "${name}.torrent" -w "$url" "$file_name"
        
      - name: Upload torrent file
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.name }}
          path: ${{ env.name }}.torrent
