name: Create torrent
on:
  push:
    branches:
      - master
      
env:
  name: "Every.Home.Should.Have.One.1970.1080p.BluRay.x264"
  comment: "Every.Home.Should.Have.One.1970.1080p.BluRay.x264"
  url: https://fr14.seedr.cc/ff_get/805087778/Every.Home.Should.Have.One.1970.1080p.BluRay.x264-[YTS.AM].mp4?st=w8aon5y_cJSYlqZqLE8Pbg&e=1608125391
  file_name: "Every.Home.Should.Have.One.1970.1080p.BluRay.x264-[YTS.AM].mp4"
  piece_size: 20 # Check the README.md for recommended piece size
      
jobs:
  create:
    runs-on: ubuntu-20.04
    steps:
      - name: Install mktorrent
        run: sudo apt-get install mktorrent
        
      - name: Download file
        run: wget -nv -O "$file_name" "$url"
        
      - name: Create torrent using mktorrent
        run: mktorrent -c "$comment" -l $piece_size -o "${name}.torrent" -w "$url" "$file_name"
        
      - name: Upload torrent file
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.name }}
          path: ${{ env.name }}.torrent
