name: Create torrent
on:
  push:
    branches:
      - master
      
env:
  name: "The.Burning.1981"
  comment: "The.Burning.1981"
  url: http://45.162.231.181:3000/download/8cabb958-a771-436f-a424-f35dbbe39618/the-burning-1981.mkv
  file_name: "The.Burning.1981.mkv"
  piece_size: 20 # Check the README.md for recommended piece size
      
jobs:
  create:
    runs-on: ubuntu-20.04
    steps:
      - name: Install mktorrent
        run: sudo apt-get install mktorrent
        
      - name: Download file
        run: wget -nv -O "$file_name" "$url"
        
      - name: Create torrent using mktorrent
        run: mktorrent -c "$comment" -l $piece_size -o "${name}.torrent" -w "$url" "$file_name"
        
      - name: Upload torrent file
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.name }}
          path: ${{ env.name }}.torrent
