name: Create torrent
on:
  push:
    branches:
      - master
      
env:
  name: "Performance.1970.1080p.BluRay.x264"
  comment: "Performance.1970.1080p.BluRay.x264"
  url: https://dlsv6.sonicbit.net/file/dl2/TXQ2UHNNQzBZWjdYdk5VbFg4eEhjUFZFTXdKclZSak9BYWc1R1k2MTJTejdSZmJwMHllOUMyQzhsbEdhNThQWGdSUWN0MFg2UllJMlhubzZzU0dWUjVENFFqWTJPU1VZc1A1eG43Q2gwaTVhV1VZM2RFSGNhdWRqL295ampNQ2FMRmZMVnVidkxsaWVJVGREL0lOdEZleGZWSlNWTy8yQ0orMFp0YUVta1lJPQ==/Performance.1970.1080p.BluRay.x264.YIFY.mp4
  file_name: "Performance.1970.1080p.BluRay.x264.YIFY.mp4"
  piece_size: 20 # Check the README.md for recommended piece size
      
jobs:
  create:
    runs-on: ubuntu-20.04
    steps:
      - name: Install mktorrent
        run: sudo apt-get install mktorrent
        
      - name: Download file
        run: wget -nv -O "$file_name" "$url"
        
      - name: Create torrent using mktorrent
        run: mktorrent -c "$comment" -l $piece_size -o "${name}.torrent" -w "$url" "$file_name"
        
      - name: Upload torrent file
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.name }}
          path: ${{ env.name }}.torrent
