name: Create torrent
on:
  push:
    branches:
      - master
      
env:
  name: "Scream.And.Scream.Again.1970.1080p.BluRay.x264"
  comment: "Scream.And.Scream.Again.1970.1080p.BluRay.x264"
  url: https://dlsvfree.sonicbit.net/file/dl2/aWgvMUZ4WnlKVnlKcURnYkY2RUFIS0NKYjlvRlF5OXEzc3BKRVJxQWoyK0Y2UzMyRS90RW1LNVVqZm5leEc1YlgrbStoY2lzTzkrQjJtK093TGJabERzbkN4UUNRZnRyK3FkMC9qWTZESDMwdVpxcm5kMHVkcUEzT2Y1TnhjU0ROZjdrN2h5Z2VNMy8yR3EwQUJnbjRqRkYrZHNhU2JkN3NZcksxMmRGQVBNVVd0MkYrSm9vQWpPWEtmUHR0SkNsa1J6L0s2ei96S1dGbTRvS3VlZTR6UT09/Scream.And.Scream.Again.1970.1080p.BluRay.x264-[YTS.AM].mp4
  file_name: "Scream.And.Scream.Again.1970.1080p.BluRay.x264-[YTS.AM].mp4"
  piece_size: 20 # Check the README.md for recommended piece size
      
jobs:
  create:
    runs-on: ubuntu-20.04
    steps:
      - name: Install mktorrent
        run: sudo apt-get install mktorrent
        
      - name: Download file
        run: wget -nv -O "$file_name" "$url"
        
      - name: Create torrent using mktorrent
        run: mktorrent -c "$comment" -l $piece_size -o "${name}.torrent" -w "$url" "$file_name"
        
      - name: Upload torrent file
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.name }}
          path: ${{ env.name }}.torrent
