name: Create torrent
on:
  push:
    branches:
      - master
      
env:
  name: "The Night Visitor (1971)"
  comment: "The Night Visitor (1971)"
  url: https://dlsv6.sonicbit.net/dl/zip2/cmZsT3ZvSk1NN0xsbFhpaGFyVTFlRnVRR0djd2JSZ3FkSDZYdDJBaXUvWDhRWUZTc2tqME1IZE00NkVYQ3o5ZFJIL2RJb2hNYTN1V3lLTzZZM1JCT1E9PQ==/31135FBBF6E947D40AB669FA0C64CE5F3A439040/The%20Night%20Visitor%20(1971)%20BluRay%20[1080p]%20[YTS.AM].zip
  file_name: "The Night Visitor (1971) [BluRay] [1080p] [YTS.AM].zip"
  piece_size: 20 # Check the README.md for recommended piece size
      
jobs:
  create:
    runs-on: ubuntu-20.04
    steps:
      - name: Install mktorrent
        run: sudo apt-get install mktorrent
        
      - name: Download file
        run: wget -nv -O "$file_name" "$url"
        
      - name: Create torrent using mktorrent
        run: mktorrent -c "$comment" -l $piece_size -o "${name}.torrent" -w "$url" "$file_name"
        
      - name: Upload torrent file
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.name }}
          path: ${{ env.name }}.torrent
