name: Create torrent
on:
  push:
    branches:
      - master
      
env:
  name: "What.1972"
  comment: "What.1972"
  url: http://45.162.231.181:3000/download/4bf3eeaf-2d27-4c98-917e-0d54e92dd23e/what-1972.mkv
  file_name: "What.1972.mkv"
  piece_size: 20 # Check the README.md for recommended piece size
      
jobs:
  create:
    runs-on: ubuntu-20.04
    steps:
      - name: Install mktorrent
        run: sudo apt-get install mktorrent
        
      - name: Download file
        run: wget -nv -O "$file_name" "$url"
        
      - name: Create torrent using mktorrent
        run: mktorrent -c "$comment" -l $piece_size -o "${name}.torrent" -w "$url" "$file_name"
        
      - name: Upload torrent file
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.name }}
          path: ${{ env.name }}.torrent
