name: Create torrent
on:
  push:
    branches:
      - master
      
env:
  name: "Bananas.1971.1080p.BluRay.x264"
  comment: "Bananas.1971.1080p.BluRay.x264"
  url: https://dlsv6.sonicbit.net/file/dl2/TXQ2UHNNQzBZWjdYdk5VbFg4eEhjUFZFTXdKclZSak9BYWc1R1k2MTJTd3Y0WEJldnI1ZHBuS1pTUWVzZ25NUHB3YmFnV2o5M2ZMVnMyRWgvYVNJTStMa0ZBVlRXbE0zTTByOEI4WkVoT2piN3I5K3kvTExoMk5KQ2trYVFTNUJSRFhlRFU5VjVFMmxJbGs5NHdmS0I3T3dBOWRtUjhrT2R3ck1VUVIwWlVVQlk3UUF1THA1Q3hFU29HMVQ1bHE0/Bananas.1971.1080p.BluRay.x264-[YTS.LT].mp4
  file_name: "Bananas.1971.1080p.BluRay.x264-[YTS.LT].mp4"
  piece_size: 20 # Check the README.md for recommended piece size
      
jobs:
  create:
    runs-on: ubuntu-20.04
    steps:
      - name: Install mktorrent
        run: sudo apt-get install mktorrent
        
      - name: Download file
        run: wget -nv -O "$file_name" "$url"
        
      - name: Create torrent using mktorrent
        run: mktorrent -c "$comment" -l $piece_size -o "${name}.torrent" -w "$url" "$file_name"
        
      - name: Upload torrent file
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.name }}
          path: ${{ env.name }}.torrent
