name: Create torrent
on:
  push:
    branches:
      - master
      
env:
  name: "Colossus.The.Forbin.Project.1970.1080p.BluRay.x264"
  comment: "Colossus.The.Forbin.Project.1970.1080p.BluRay.x264"
  url: https://fr15.seedr.cc/ff_get/803882418/Colossus.The.Forbin.Project.1970.1080p.BluRay.x264-[YTS.AG].mp4?st=rH31jtqZKSes5-IQWYEPhQ&e=1607966301
  file_name: "Colossus.The.Forbin.Project.1970.1080p.BluRay.x264-[YTS.AG].mp4"
  piece_size: 20 # Check the README.md for recommended piece size
      
jobs:
  create:
    runs-on: ubuntu-20.04
    steps:
      - name: Install mktorrent
        run: sudo apt-get install mktorrent
        
      - name: Download file
        run: wget -nv -O "$file_name" "$url"
        
      - name: Create torrent using mktorrent
        run: mktorrent -c "$comment" -l $piece_size -o "${name}.torrent" -w "$url" "$file_name"
        
      - name: Upload torrent file
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.name }}
          path: ${{ env.name }}.torrent
