name: Create torrent
on:
  push:
    branches:
      - master
      
env:
  name: "NeXt.2020.S01E07.WEB.x264"
  comment: "NeXt.2020.S01E07.WEB.x264"
  url: https://dlsv6.sonicbit.net/dl/zip2/Q3VJSzduaTdjTWtOYWVuck9lMXUwSkN5dlhiNHR0N3F4K0E3R1cvZ28vc1NpL3NZTG00WnY0SGM0OTFRaklkbGFYUGI1L2JaV2pCU1N1bWY0d2VHWWc9PQ==/6A8SG9A6G87AS78G6/NeXt.2020.S01E07.WEB.x264-PHOENiXTGx.zip
  file_name: "NeXt.2020.S01E07.WEB.x264-PHOENiX[TGx].zip"
  piece_size: 20 # Check the README.md for recommended piece size
      
jobs:
  create:
    runs-on: ubuntu-20.04
    steps:
      - name: Install mktorrent
        run: sudo apt-get install mktorrent
        
      - name: Download file
        run: wget -nv -O "$file_name" "$url"
        
      - name: Create torrent using mktorrent
        run: mktorrent -c "$comment" -l $piece_size -o "${name}.torrent" -w "$url" "$file_name"
        
      - name: Upload torrent file
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.name }}
          path: ${{ env.name }}.torrent
