name: Create torrent
on:
  push:
    branches:
      - master
      
env:
  name: "And.Soon.The.Darkness.1970.1080p.BluRay.x264"
  comment: "And.Soon.The.Darkness.1970.1080p.BluRay.x264"
  url: https://doc-04-74-docs.googleusercontent.com/docs/securesc/lqephelp3ehdhfrs6ka9220p7liahudg/jbt3ee20511113shptimbrespfm5ald1/1607867850000/09670154100834795402/09670154100834795402/1IPPO--ODuAhY358Lqm6ZwY6dvRzTttmM?e=download&authuser=0
  file_name: "And.Soon.The.Darkness.1970.1080p.BluRay.x264-[YTS.LT].mp4"
  piece_size: 20 # Check the README.md for recommended piece size
      
jobs:
  create:
    runs-on: ubuntu-20.04
    steps:
      - name: Install mktorrent
        run: sudo apt-get install mktorrent
        
      - name: Download file
        run: wget -nv -O "$file_name" "$url"
        
      - name: Create torrent using mktorrent
        run: mktorrent -c "$comment" -l $piece_size -o "${name}.torrent" -w "$url" "$file_name"
        
      - name: Upload torrent file
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.name }}
          path: ${{ env.name }}.torrent
