name: Create torrent
on:
  push:
    branches:
      - master
      
env:
  name: "Such Good Friends (1971)"
  comment: "Such Good Friends (1971)"
  url: https://dlsv6.sonicbit.net/dl/zip2/QncyMHgwb3RnSG4zVGNEUzUzMHlPYysvZFNBMDJKd0JZS2o4NVJrZTMwR1c0ZXdHSldHaFE1MXFBbDRnanE4bS9DYTYvVjl5NmtIcG84blozQkc1Vmc9PQ==/E825D65ED344817F0A1976CA3DF95E50DEF6A11D/Such%20Good%20Friends%20(1971)%201080p%20[YTS.AG].zip
  file_name: "Such Good Friends (1971) [1080p] [YTS.AG].zip"
  piece_size: 20 # Check the README.md for recommended piece size
      
jobs:
  create:
    runs-on: ubuntu-20.04
    steps:
      - name: Install mktorrent
        run: sudo apt-get install mktorrent
        
      - name: Download file
        run: wget -nv -O "$file_name" "$url"
        
      - name: Create torrent using mktorrent
        run: mktorrent -c "$comment" -l $piece_size -o "${name}.torrent" -w "$url" "$file_name"
        
      - name: Upload torrent file
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.name }}
          path: ${{ env.name }}.torrent
